#include "C_TeamCard.h"
#include "Components/TextBlock.h"
#include "Components/VerticalBox.h"
#include "Components/WrapBox.h"
#include "Components/Button.h"
#include "../Components/TeamComponent.h"
#include "../Components/LocationMovementComponent.h"
#include "../Components/InventoryComponent.h"
#include "../Components/TaskManagerComponent.h"
#include "../Components/TimeManagerComponent.h"
#include "../Actor/C_IdleCharacter.h"
#include "../C_PlayerController.h"
#include "C_CharacterCard.h"
#include "C_TeamTaskCard.h"
#include "Framework/Application/SlateApplication.h"

UC_TeamCard::UC_TeamCard(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
{
    TeamIndex = -1;
    TeamComponent = nullptr;
    bIsInitialized = false;
    
    // Team card created
}

void UC_TeamCard::NativeConstruct()
{
    Super::NativeConstruct();
    
    // Team card constructed
    
    if (CharacterCardsContainer)
    {
        // UE_LOG(LogTemp, Warning, TEXT("UC_TeamCard::NativeConstruct - CharacterCardsContainer found"));
    }
    else
    {
        UE_LOG(LogTemp, Error, TEXT("UC_TeamCard::NativeConstruct - CharacterCardsContainer is NULL! Check Blueprint binding"));
    }
    
    // ãƒãƒ¼ãƒ ã‚¿ã‚¹ã‚¯ä½œæˆãƒœã‚¿ãƒ³ã®ãƒã‚¤ãƒ³ãƒ‰
    if (CreateTaskButton)
    {
        CreateTaskButton->OnClicked.AddDynamic(this, &UC_TeamCard::OnCreateTaskClicked);
        // UE_LOG(LogTemp, Warning, TEXT("UC_TeamCard::NativeConstruct - CreateTaskButton bound"));
    }
    else
    {
        UE_LOG(LogTemp, VeryVerbose, TEXT("UC_TeamCard::NativeConstruct - CreateTaskButton is NULL (optional)"));
    }
    
    // CharacterCardClassãŒè¨­å®šã•ã‚Œã¦ã„ãªã„å ´åˆã¯è‡ªå‹•è¨­å®šã‚’è©¦è¡Œ
    if (!CharacterCardClass)
    {
        UE_LOG(LogTemp, VeryVerbose, TEXT("UC_TeamCard::NativeConstruct - CharacterCardClass not set, trying to auto-detect"));
        CharacterCardClass = UC_CharacterCard::StaticClass();
        if (CharacterCardClass)
        {
            UE_LOG(LogTemp, VeryVerbose, TEXT("UC_TeamCard::NativeConstruct - Auto-set CharacterCardClass to UC_CharacterCard"));
        }
        else
        {
            UE_LOG(LogTemp, Error, TEXT("UC_TeamCard::NativeConstruct - Failed to auto-set CharacterCardClass"));
        }
    }
    else
    {
        // UE_LOG(LogTemp, Warning, TEXT("UC_TeamCard::NativeConstruct - CharacterCardClass is already set"));
    }
    
    // TeamTaskMakeSheetClassãŒè¨­å®šã•ã‚Œã¦ã„ãªã„å ´åˆã¯è‡ªå‹•è¨­å®šã‚’è©¦è¡Œ
    if (!TeamTaskMakeSheetClass)
    {
        UE_LOG(LogTemp, VeryVerbose, TEXT("UC_TeamCard::NativeConstruct - TeamTaskMakeSheetClass not set, trying to auto-detect"));
        TeamTaskMakeSheetClass = UC_TeamTaskMakeSheet::StaticClass();
        if (TeamTaskMakeSheetClass)
        {
            UE_LOG(LogTemp, VeryVerbose, TEXT("UC_TeamCard::NativeConstruct - Auto-set TeamTaskMakeSheetClass to UC_TeamTaskMakeSheet"));
        }
        else
        {
            UE_LOG(LogTemp, Error, TEXT("UC_TeamCard::NativeConstruct - Failed to auto-set TeamTaskMakeSheetClass"));
        }
    }
    else
    {
        // UE_LOG(LogTemp, Warning, TEXT("UC_TeamCard::NativeConstruct - TeamTaskMakeSheetClass is already set"));
    }
    
    // TeamTaskCardClassãŒè¨­å®šã•ã‚Œã¦ã„ãªã„å ´åˆã¯è‡ªå‹•è¨­å®šã‚’è©¦è¡Œ
    if (!TeamTaskCardClass)
    {
        UE_LOG(LogTemp, VeryVerbose, TEXT("UC_TeamCard::NativeConstruct - TeamTaskCardClass not set, trying to auto-detect"));
        TeamTaskCardClass = UC_TeamTaskCard::StaticClass();
        if (TeamTaskCardClass)
        {
            UE_LOG(LogTemp, VeryVerbose, TEXT("UC_TeamCard::NativeConstruct - Auto-set TeamTaskCardClass to UC_TeamTaskCard"));
        }
        else
        {
            UE_LOG(LogTemp, Error, TEXT("UC_TeamCard::NativeConstruct - Failed to auto-set TeamTaskCardClass"));
        }
    }
}

void UC_TeamCard::NativeDestruct()
{
    UnbindTeamEvents();
    ClearCharacterCards();
    ClearTaskCards();

    // ãƒœã‚¿ãƒ³ã‚¤ãƒ™ãƒ³ãƒˆã®ã‚¢ãƒ³ãƒã‚¤ãƒ³ãƒ‰
    if (CreateTaskButton)
    {
        CreateTaskButton->OnClicked.RemoveDynamic(this, &UC_TeamCard::OnCreateTaskClicked);
    }

    Super::NativeDestruct();
}

void UC_TeamCard::InitializeWithTeam(int32 InTeamIndex, UTeamComponent* InTeamComponent)
{
    if (!InTeamComponent)
    {
        UE_LOG(LogTemp, Warning, TEXT("UC_TeamCard::InitializeWithTeam - InTeamComponent is null"));
        return;
    }

    if (!InTeamComponent->IsValidTeamIndex(InTeamIndex))
    {
        UE_LOG(LogTemp, Warning, TEXT("UC_TeamCard::InitializeWithTeam - Invalid team index: %d"), InTeamIndex);
        return;
    }

    // æ—¢å­˜ã®ã‚¤ãƒ™ãƒ³ãƒˆãƒã‚¤ãƒ³ãƒ‰ã‚’è§£é™¤
    UnbindTeamEvents();

    TeamIndex = InTeamIndex;
    TeamComponent = InTeamComponent;
    bIsInitialized = true;

    // æ–°ã—ã„TeamComponentã®ã‚¤ãƒ™ãƒ³ãƒˆã«ãƒã‚¤ãƒ³ãƒ‰
    BindTeamEvents();

    // åˆå›è¡¨ç¤ºæ›´æ–°
    UpdateDisplay();
}

void UC_TeamCard::UpdateDisplay()
{
    if (!bIsInitialized || !IsValidTeamCard())
    {
        return;
    }

    UpdateTeamInfo();
    UpdateCharacterCards();
    UpdateTaskCards();
}

void UC_TeamCard::UpdateTeamInfo()
{
    if (!IsValidTeamCard())
    {
        return;
    }

    UpdateTeamNameDisplay();
    UpdateCurrentTaskDisplay();
    UpdateTeamStatusDisplay();
    UpdateMemberCountDisplay();
    UpdateDistanceFromBaseDisplay();
}

void UC_TeamCard::UpdateCharacterCards()
{
    // Character cards update start
    
    if (!IsValidTeamCard())
    {
        UE_LOG(LogTemp, Error, TEXT("UC_TeamCard::UpdateCharacterCards - Invalid team card"));
        return;
    }
    
    if (!CharacterCardsContainer)
    {
        UE_LOG(LogTemp, Error, TEXT("UC_TeamCard::UpdateCharacterCards - CharacterCardsContainer is NULL"));
        return;
    }

    // UE_LOG(LogTemp, Warning, TEXT("UC_TeamCard::UpdateCharacterCards - Clearing existing cards"));
    // æ—¢å­˜ã®ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã‚«ãƒ¼ãƒ‰ã‚’ã‚¯ãƒªã‚¢
    ClearCharacterCards();

    // ãƒãƒ¼ãƒ ãƒ¡ãƒ³ãƒãƒ¼ã®ã‚«ãƒ¼ãƒ‰ã‚’ä½œæˆ
    FTeam TeamData = GetTeamData();
    UE_LOG(LogTemp, VeryVerbose, TEXT("UC_TeamCard::UpdateCharacterCards - Team has %d members"), TeamData.Members.Num());
    
    for (int32 i = 0; i < TeamData.Members.Num(); ++i)
    {
        AC_IdleCharacter* Character = TeamData.Members[i];
        if (Character)
        {
            // UE_LOG(LogTemp, Warning, TEXT("UC_TeamCard::UpdateCharacterCards - Creating card for member %d"), i);
            UC_CharacterCard* CharacterCard = CreateCharacterCard(Character);
            if (CharacterCard)
            {
                CharacterCards.Add(CharacterCard);
                CharacterCardsContainer->AddChildToWrapBox(CharacterCard);
                // UE_LOG(LogTemp, Warning, TEXT("UC_TeamCard::UpdateCharacterCards - Successfully added character card %d to container"), i);
            }
            else
            {
                UE_LOG(LogTemp, Error, TEXT("UC_TeamCard::UpdateCharacterCards - Failed to create character card for member %d"), i);
            }
        }
        else
        {
            UE_LOG(LogTemp, Error, TEXT("UC_TeamCard::UpdateCharacterCards - Member %d is NULL"), i);
        }
    }
    
    // Character cards update end
}

void UC_TeamCard::UpdateTaskCards()
{
    // Updating task cards
    
    if (!IsValidTeamCard() || !TeamTaskCardsContainer)
    {
        UE_LOG(LogTemp, Error, TEXT("UC_TeamCard::UpdateTaskCards - Invalid team card or container"));
        return;
    }

    // æ—¢å­˜ã®ã‚¿ã‚¹ã‚¯ã‚«ãƒ¼ãƒ‰ã‚’ã‚¯ãƒªã‚¢
    ClearTaskCards();

    // ãƒãƒ¼ãƒ ã‚¿ã‚¹ã‚¯ã®ã‚«ãƒ¼ãƒ‰ã‚’ä½œæˆ
    TArray<FTeamTask> TeamTasks = TeamComponent->GetTeamTasks(TeamIndex);
    // Found tasks
    
    for (int32 i = 0; i < TeamTasks.Num(); ++i)
    {
        UC_TeamTaskCard* TaskCard = CreateTaskCard(TeamTasks[i], i);
        if (TaskCard)
        {
            TeamTaskCards.Add(TaskCard);
            TeamTaskCardsContainer->AddChildToVerticalBox(TaskCard);
            // Task card added
        }
        else
        {
            UE_LOG(LogTemp, Error, TEXT("UC_TeamCard::UpdateTaskCards - Failed to create task card %d"), i);
        }
    }
    
    // Task cards update completed
}

FTeam UC_TeamCard::GetTeamData() const
{
    if (IsValidTeamCard())
    {
        return TeamComponent->GetTeam(TeamIndex);
    }
    return FTeam();
}

bool UC_TeamCard::IsValidTeamCard() const
{
    return bIsInitialized && 
           TeamComponent && 
           TeamComponent->IsValidTeamIndex(TeamIndex);
}

void UC_TeamCard::BindTeamEvents()
{
    if (!TeamComponent)
    {
        UE_LOG(LogTemp, Error, TEXT("BindTeamEvents: TeamComponent is NULL for TeamCard %d"), TeamIndex);
        return;
    }

    TeamComponent->OnMemberAssigned.AddDynamic(this, &UC_TeamCard::OnMemberAssigned);
    TeamComponent->OnMemberRemoved.AddDynamic(this, &UC_TeamCard::OnMemberRemoved);
    TeamComponent->OnTaskChanged.AddDynamic(this, &UC_TeamCard::OnTaskChanged);
    TeamComponent->OnTeamNameChanged.AddDynamic(this, &UC_TeamCard::OnTeamNameChanged);
    TeamComponent->OnTeamActionStateChanged.AddDynamic(this, &UC_TeamCard::OnTeamActionStateChanged);
    TeamComponent->OnTeamTaskStarted.AddDynamic(this, &UC_TeamCard::OnTeamTaskStarted);
    TeamComponent->OnTeamTaskCompleted.AddDynamic(this, &UC_TeamCard::OnTeamTaskCompleted);
    TeamComponent->OnCharacterDataChanged.AddDynamic(this, &UC_TeamCard::OnCharacterDataChanged);
    TeamComponent->OnTeamsUpdated.AddDynamic(this, &UC_TeamCard::OnTeamsUpdated);
    
    // MovementComponentã®ã‚¤ãƒ™ãƒ³ãƒˆã‚‚ãƒã‚¤ãƒ³ãƒ‰
    if (UWorld* World = GetWorld())
    {
        if (APlayerController* PC = World->GetFirstPlayerController())
        {
            if (AC_PlayerController* IdlePC = Cast<AC_PlayerController>(PC))
            {
                if (ULocationMovementComponent* MovementComp = IdlePC->MovementComponent)
                {
                    MovementComp->OnMovementProgressUpdated.AddDynamic(this, &UC_TeamCard::OnMovementProgressUpdated);
                }
            }
        }
    }
}

void UC_TeamCard::UnbindTeamEvents()
{
    if (!TeamComponent)
    {
        return;
    }

    TeamComponent->OnMemberAssigned.RemoveDynamic(this, &UC_TeamCard::OnMemberAssigned);
    TeamComponent->OnMemberRemoved.RemoveDynamic(this, &UC_TeamCard::OnMemberRemoved);
    TeamComponent->OnTaskChanged.RemoveDynamic(this, &UC_TeamCard::OnTaskChanged);
    TeamComponent->OnTeamNameChanged.RemoveDynamic(this, &UC_TeamCard::OnTeamNameChanged);
    TeamComponent->OnTeamActionStateChanged.RemoveDynamic(this, &UC_TeamCard::OnTeamActionStateChanged);
    TeamComponent->OnTeamTaskStarted.RemoveDynamic(this, &UC_TeamCard::OnTeamTaskStarted);
    TeamComponent->OnTeamTaskCompleted.RemoveDynamic(this, &UC_TeamCard::OnTeamTaskCompleted);
    TeamComponent->OnCharacterDataChanged.RemoveDynamic(this, &UC_TeamCard::OnCharacterDataChanged);
    TeamComponent->OnTeamsUpdated.RemoveDynamic(this, &UC_TeamCard::OnTeamsUpdated);
    
    // MovementComponentã®ã‚¤ãƒ™ãƒ³ãƒˆã‚‚ã‚¢ãƒ³ãƒã‚¤ãƒ³ãƒ‰
    if (UWorld* World = GetWorld())
    {
        if (APlayerController* PC = World->GetFirstPlayerController())
        {
            if (AC_PlayerController* IdlePC = Cast<AC_PlayerController>(PC))
            {
                if (ULocationMovementComponent* MovementComp = IdlePC->MovementComponent)
                {
                    MovementComp->OnMovementProgressUpdated.RemoveDynamic(this, &UC_TeamCard::OnMovementProgressUpdated);
                }
            }
        }
    }
}

void UC_TeamCard::OnMemberAssigned(int32 InTeamIndex, AC_IdleCharacter* Character, const FString& TeamName)
{
    if (InTeamIndex == TeamIndex)
    {
        UE_LOG(LogTemp, Log, TEXT("UC_TeamCard::OnMemberAssigned - Team %d"), TeamIndex);
        UpdateCharacterCards();
        UpdateMemberCountDisplay();
    }
}

void UC_TeamCard::OnMemberRemoved(int32 InTeamIndex, AC_IdleCharacter* Character)
{
    if (InTeamIndex == TeamIndex)
    {
        UE_LOG(LogTemp, Log, TEXT("UC_TeamCard::OnMemberRemoved - Team %d"), TeamIndex);
        UpdateCharacterCards();
        UpdateMemberCountDisplay();
    }
}

void UC_TeamCard::OnTaskChanged(int32 InTeamIndex, ETaskType NewTask)
{
    if (InTeamIndex == TeamIndex)
    {
        UE_LOG(LogTemp, Log, TEXT("UC_TeamCard::OnTaskChanged - Team %d"), TeamIndex);
        UpdateCurrentTaskDisplay();
        UpdateTeamStatusDisplay();
    }
}

void UC_TeamCard::OnTeamNameChanged(int32 InTeamIndex, const FString& NewName)
{
    if (InTeamIndex == TeamIndex)
    {
        UE_LOG(LogTemp, Log, TEXT("UC_TeamCard::OnTeamNameChanged - Team %d: %s"), TeamIndex, *NewName);
        UpdateTeamNameDisplay();
    }
}

void UC_TeamCard::OnTeamActionStateChanged(int32 InTeamIndex, ETeamActionState NewState)
{
    if (InTeamIndex == TeamIndex)
    {
        UpdateTeamStatusDisplay();
    }
}

void UC_TeamCard::OnTeamTaskStarted(int32 InTeamIndex, const FTeamTask& StartedTask)
{
    UE_LOG(LogTemp, VeryVerbose, TEXT("UC_TeamCard::OnTeamTaskStarted - Called for Team %d, My Team: %d"), InTeamIndex, TeamIndex);
    
    if (InTeamIndex == TeamIndex)
    {
        UE_LOG(LogTemp, VeryVerbose, TEXT("UC_TeamCard::OnTeamTaskStarted - Updating task cards for Team %d"), TeamIndex);
        UpdateTaskCards();
        UpdateCurrentTaskDisplay();
    }
}

void UC_TeamCard::OnTeamTaskCompleted(int32 InTeamIndex, const FTeamTask& CompletedTask)
{
    if (InTeamIndex == TeamIndex)
    {
        UE_LOG(LogTemp, Log, TEXT("UC_TeamCard::OnTeamTaskCompleted - Team %d"), TeamIndex);
        UpdateTaskCards();
        UpdateCurrentTaskDisplay();
    }
}

void UC_TeamCard::OnCharacterDataChanged(AC_IdleCharacter* Character)
{
    // ã“ã®ãƒãƒ¼ãƒ ã®ãƒ¡ãƒ³ãƒãƒ¼ã‹ãƒã‚§ãƒƒã‚¯
    FTeam TeamData = GetTeamData();
    if (TeamData.Members.Contains(Character))
    {
        UE_LOG(LogTemp, Log, TEXT("UC_TeamCard::OnCharacterDataChanged - Team %d"), TeamIndex);
        UpdateCharacterCards();
    }
}

void UC_TeamCard::OnTeamsUpdated()
{
    // ã‚¢ã‚¤ãƒ†ãƒ æ¡é›†ç­‰ã§ãƒãƒ¼ãƒ çŠ¶æ…‹ãŒå¤‰ã‚ã£ãŸå¯èƒ½æ€§ãŒã‚ã‚‹ãŸã‚ã€å…¨ã¦ã®è¡¨ç¤ºã‚’æ›´æ–°
    UpdateTeamStatusDisplay();
    UpdateCurrentTaskDisplay();
    UpdateCharacterCards();
}

void UC_TeamCard::OnMovementProgressUpdated(int32 InTeamIndex, const FMovementInfo& MovementInfo)
{
    // è‡ªåˆ†ã®ãƒãƒ¼ãƒ ã®ç§»å‹•é€²æ—ã®ã¿å‡¦ç†
    if (InTeamIndex == TeamIndex)
    {
        UE_LOG(LogTemp, VeryVerbose, TEXT("C_TeamCard: Movement progress update for team %d - distance: %.1fm, remaining: %.1fs"), 
            InTeamIndex, MovementInfo.CurrentDistanceFromBase, MovementInfo.RemainingTime);
        
        // ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ã¨è·é›¢è¡¨ç¤ºã‚’æ›´æ–°
        UpdateTeamStatusDisplay();
        UpdateDistanceFromBaseDisplay();
    }
}

void UC_TeamCard::ClearCharacterCards()
{
    if (CharacterCardsContainer)
    {
        CharacterCardsContainer->ClearChildren();
    }

    for (UC_CharacterCard* Card : CharacterCards)
    {
        if (Card)
        {
            Card->RemoveFromParent();
        }
    }

    CharacterCards.Empty();
}

void UC_TeamCard::ClearTaskCards()
{
    if (TeamTaskCardsContainer)
    {
        TeamTaskCardsContainer->ClearChildren();
    }

    for (UC_TeamTaskCard* Card : TeamTaskCards)
    {
        if (Card)
        {
            Card->RemoveFromParent();
        }
    }

    TeamTaskCards.Empty();
}

UC_CharacterCard* UC_TeamCard::CreateCharacterCard(AC_IdleCharacter* Character)
{
    UE_LOG(LogTemp, VeryVerbose, TEXT("UC_TeamCard::CreateCharacterCard - START"));
    
    if (!Character)
    {
        UE_LOG(LogTemp, Error, TEXT("UC_TeamCard::CreateCharacterCard - Character is null"));
        return nullptr;
    }
    
    if (!CharacterCardClass)
    {
        UE_LOG(LogTemp, Error, TEXT("UC_TeamCard::CreateCharacterCard - CharacterCardClass is null! Check Blueprint settings"));
        return nullptr;
    }

    UE_LOG(LogTemp, VeryVerbose, TEXT("UC_TeamCard::CreateCharacterCard - Creating widget with class"));
    UC_CharacterCard* NewCard = CreateWidget<UC_CharacterCard>(this, CharacterCardClass);
    
    if (NewCard)
    {
        // Widget created successfully
        NewCard->InitializeWithCharacter(Character);
        // Character card initialized
    }
    else
    {
        UE_LOG(LogTemp, Error, TEXT("UC_TeamCard::CreateCharacterCard - Failed to create widget"));
    }

    return NewCard;
}

UC_TeamTaskCard* UC_TeamCard::CreateTaskCard(const FTeamTask& TaskData, int32 TaskPriority)
{
    if (!TeamTaskCardClass)
    {
        UE_LOG(LogTemp, VeryVerbose, TEXT("UC_TeamCard::CreateTaskCard - TeamTaskCardClass is null"));
        return nullptr;
    }

    UC_TeamTaskCard* NewCard = CreateWidget<UC_TeamTaskCard>(this, TeamTaskCardClass);
    if (NewCard)
    {
        NewCard->InitializeWithTeamTask(TaskData, TeamIndex, TaskPriority, TeamComponent);
    }

    return NewCard;
}

FString UC_TeamCard::GetCurrentTaskDisplayText() const
{
    if (!IsValidTeamCard())
    {
        return TEXT("ç„¡åŠ¹ãªãƒãƒ¼ãƒ ");
    }

    FTeam TeamData = GetTeamData();
    
    // ç¾åœ¨å®Ÿè¡Œä¸­ã®ã‚¿ã‚¹ã‚¯ã‚’å–å¾—
    FTeamTask CurrentTask = TeamComponent->GetCurrentTeamTask(TeamIndex);
    if (CurrentTask.TaskType != ETaskType::Idle)
    {
        return UTaskTypeUtils::GetTaskTypeDisplayName(CurrentTask.TaskType);
    }

    // å‰²ã‚Šå½“ã¦ã‚‰ã‚ŒãŸã‚¿ã‚¹ã‚¯ã‚’è¡¨ç¤º
    if (TeamData.AssignedTask != ETaskType::Idle)
    {
        return UTaskTypeUtils::GetTaskTypeDisplayName(TeamData.AssignedTask);
    }

    return TEXT("å¾…æ©Ÿä¸­");
}

FString UC_TeamCard::GetTeamStatusDisplayText() const
{
    if (!IsValidTeamCard())
    {
        return TEXT("ç„¡åŠ¹");
    }

    // === æ¯ã‚¿ãƒ¼ãƒ³åˆ¤å®šãƒ­ã‚¸ãƒƒã‚¯ï¼ˆçŠ¶æ…‹ç®¡ç†ãªã—ï¼‰ ===
    
    // 1. ç¾åœ¨åœ°ã‚’å–å¾—
    FString CurrentLocation = GetCurrentLocation();
    
    // 2. TaskManagerã‹ã‚‰å®Ÿè¡Œå¯èƒ½ã‚¿ã‚¹ã‚¯ã‚’ç¢ºèª
    FString TargetItem = GetCurrentTargetItem();
    
    // 3. ç§»å‹•ä¸­ã‹ãƒã‚§ãƒƒã‚¯
    bool bIsMoving = IsTeamMoving();
    
    // 4. ãƒ­ã‚¸ãƒƒã‚¯åˆ†å²
    if (CurrentLocation == TEXT("base"))
    {
        // æ‹ ç‚¹ã«ã„ã‚‹å ´åˆ
        if (bIsMoving)
        {
            // ç§»å‹•æº–å‚™ä¸­ã¾ãŸã¯ç§»å‹•é–‹å§‹
            return GetMovementStatusText(false); // ç§»å‹•
        }
        else if (ShouldUnloadItems())
        {
            return TEXT("è·ä¸‹ã‚ã—");
        }
        else if (!TargetItem.IsEmpty())
        {
            // æ–°ã—ã„ã‚¿ã‚¹ã‚¯ãŒã‚ã‚‹å ´åˆ
            return GetMovementStatusText(false); // ç§»å‹•
        }
        else
        {
            return TEXT("å¾…æ©Ÿ");
        }
    }
    else
    {
        // æ‹ ç‚¹ä»¥å¤–ã«ã„ã‚‹å ´åˆ
        if (bIsMoving)
        {
            // ç§»å‹•ä¸­
            if (TargetItem.IsEmpty())
            {
                return GetMovementStatusText(true); // å¸°é‚„
            }
            else
            {
                return GetMovementStatusText(false); // ç›®çš„åœ°ã«å‘ã‹ã£ã¦ç§»å‹•ä¸­
            }
        }
        else
        {
            // æ‹ ç‚¹ä»¥å¤–ã§ç§»å‹•ã—ã¦ã„ãªã„å ´åˆï¼šä½œæ¥­ä¸­ã¾ãŸã¯å¸°é‚„å¾…æ©Ÿ
            int32 CurrentResourceCount = GetCurrentResourceCount();
            
            // ãƒãƒ¼ãƒ ãŒå®Ÿéš›ã«ã‚¢ã‚¤ãƒ†ãƒ ã‚’æŒã£ã¦ã„ã‚‹ã‹ãƒã‚§ãƒƒã‚¯
            bool bHasItems = ShouldUnloadItems();
            
            if (!TargetItem.IsEmpty())
            {
                // ã‚¿ã‚¹ã‚¯ãŒã‚ã‚‹å ´åˆã¯ä½œæ¥­ä¸­ï¼ˆæ¡é›†ä¸­ï¼‰
                if (CurrentResourceCount >= 0)
                {
                    return FString::Printf(TEXT("æ¡é›†ï¼ˆ%då€‹ï¼‰"), CurrentResourceCount);
                }
                else
                {
                    return TEXT("æ¡é›†");
                }
            }
            else if (bHasItems)
            {
                // ã‚¿ã‚¹ã‚¯ã¯ãªã„ãŒã‚¢ã‚¤ãƒ†ãƒ ã‚’æŒã£ã¦ã„ã‚‹å ´åˆ
                if (CurrentResourceCount >= 0)
                {
                    return FString::Printf(TEXT("ä½œæ¥­å®Œäº†ï¼ˆ%då€‹ï¼‰"), CurrentResourceCount);
                }
                else
                {
                    return TEXT("ä½œæ¥­å®Œäº†");
                }
            }
            else
            {
                // ã‚¿ã‚¹ã‚¯ã‚‚ã‚¢ã‚¤ãƒ†ãƒ ã‚‚ãªã„å ´åˆã¯å¸°é‚„
                return GetMovementStatusText(true); // å¸°é‚„
            }
        }
    }
}

FString UC_TeamCard::GetDistanceFromBaseDisplayText() const
{
    if (!IsValidTeamCard())
    {
        return TEXT("0");
    }

    // PlayerControllerã‹ã‚‰MovementComponentã‚’å–å¾—
    if (UWorld* World = GetWorld())
    {
        if (APlayerController* PC = World->GetFirstPlayerController())
        {
            // AC_PlayerControllerã«ã‚­ãƒ£ã‚¹ãƒˆ
            if (AC_PlayerController* IdlePC = Cast<AC_PlayerController>(PC))
            {
                if (ULocationMovementComponent* MovementComp = IdlePC->MovementComponent)
                {
                    float CurrentDistance = MovementComp->GetCurrentDistanceFromBase(TeamIndex);
                    return FString::Printf(TEXT("%.0f"), CurrentDistance);
                }
            }
        }
    }

    // MovementComponentãŒå–å¾—ã§ããªã„å ´åˆã®ãƒ•ã‚©ãƒ¼ãƒ«ãƒãƒƒã‚¯
    return TEXT("0");
}

int32 UC_TeamCard::GetCurrentResourceCount() const
{
    if (!IsValidTeamCard())
    {
        return -1;
    }

    FTeam TeamData = GetTeamData();
    
    // æ¡é›†ã‚¿ã‚¹ã‚¯ã§ãªã„å ´åˆã¯-1ã‚’è¿”ã™
    if (TeamData.AssignedTask != ETaskType::Gathering)
    {
        return -1;
    }
    
    // TaskManagerComponentã‹ã‚‰ç›®æ¨™ã‚¢ã‚¤ãƒ†ãƒ IDã‚’å–å¾—
    FString TargetItemId;
    if (UWorld* World = GetWorld())
    {
        if (APlayerController* PC = World->GetFirstPlayerController())
        {
            if (AC_PlayerController* IdlePC = Cast<AC_PlayerController>(PC))
            {
                if (UTaskManagerComponent* TaskManagerComp = IdlePC->GetTaskManager())
                {
                    // ç¾åœ¨ã®æ¡é›†å ´æ‰€ã§ã®ç›®æ¨™ã‚¢ã‚¤ãƒ†ãƒ ã‚’å–å¾—
                    TargetItemId = TaskManagerComp->GetTargetItemForTeam(TeamIndex, TeamData.GatheringLocationId);
                }
            }
        }
    }
    
    if (TargetItemId.IsEmpty())
    {
        return -1; // ç›®æ¨™ã‚¢ã‚¤ãƒ†ãƒ ãŒè¨­å®šã•ã‚Œã¦ã„ãªã„
    }
    
    // ãƒãƒ¼ãƒ å†…ã®å…¨ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ãŒæŒã¤ç›®æ¨™ã‚¢ã‚¤ãƒ†ãƒ ã®å€‹æ•°ã‚’åˆè¨ˆ
    int32 TotalCount = 0;
    for (AC_IdleCharacter* Member : TeamData.Members)
    {
        if (Member && Member->GetInventoryComponent())
        {
            UInventoryComponent* CharInventory = Member->GetInventoryComponent();
            int32 MemberCount = CharInventory->GetItemCount(TargetItemId);
            TotalCount += MemberCount;
        }
    }
    
    return TotalCount;
}

void UC_TeamCard::UpdateTeamNameDisplay()
{
    if (TeamNameText)
    {
        FTeam TeamData = GetTeamData();
        TeamNameText->SetText(FText::FromString(TeamData.TeamName));
    }
}

void UC_TeamCard::UpdateCurrentTaskDisplay()
{
    if (CurrentTaskText)
    {
        FString TaskText = GetCurrentTaskDisplayText();
        CurrentTaskText->SetText(FText::FromString(TaskText));
    }
}

void UC_TeamCard::UpdateTeamStatusDisplay()
{
    if (TeamStatusText)
    {
        FString StatusText = GetTeamStatusDisplayText();
        TeamStatusText->SetText(FText::FromString(StatusText));
    }
    else
    {
        UE_LOG(LogTemp, Error, TEXT("UpdateTeamStatusDisplay: Team %d TeamStatusText is NULL"), TeamIndex);
    }
}

void UC_TeamCard::UpdateMemberCountDisplay()
{
    if (MemberCountText)
    {
        FTeam TeamData = GetTeamData();
        FString CountText = FString::Printf(TEXT("ãƒ¡ãƒ³ãƒãƒ¼: %däºº"), TeamData.Members.Num());
        MemberCountText->SetText(FText::FromString(CountText));
    }
}

void UC_TeamCard::UpdateDistanceFromBaseDisplay()
{
    if (DistanceFromBaseText)
    {
        FString DistanceText = GetDistanceFromBaseDisplayText();
        DistanceFromBaseText->SetText(FText::FromString(DistanceText));
    }
}

// ======== ãƒãƒ¼ãƒ ã‚¿ã‚¹ã‚¯ä½œæˆãƒœã‚¿ãƒ³ãƒãƒ³ãƒ‰ãƒ©ãƒ¼ ========

void UC_TeamCard::OnCreateTaskClicked()
{
    UE_LOG(LogTemp, VeryVerbose, TEXT("UC_TeamCard::OnCreateTaskClicked - Team %d"), TeamIndex);
    
    if (!IsValidTeamCard())
    {
        UE_LOG(LogTemp, Error, TEXT("UC_TeamCard::OnCreateTaskClicked - Invalid team card"));
        return;
    }
    
    // TeamTaskMakeSheetã‚’è¡¨ç¤º
    ShowTeamTaskMakeSheet();
}

void UC_TeamCard::ShowTeamTaskMakeSheet()
{
    UE_LOG(LogTemp, VeryVerbose, TEXT("UC_TeamCard::ShowTeamTaskMakeSheet - Creating task make sheet for Team %d"), TeamIndex);
    
    if (!IsValidTeamCard())
    {
        UE_LOG(LogTemp, Error, TEXT("UC_TeamCard::ShowTeamTaskMakeSheet - Invalid team card"));
        return;
    }
    
    if (!TeamTaskMakeSheetClass)
    {
        UE_LOG(LogTemp, Error, TEXT("UC_TeamCard::ShowTeamTaskMakeSheet - TeamTaskMakeSheetClass is null! Check Blueprint settings"));
        return;
    }
    
    // PlayerControllerã‚’å–å¾—ã—ã¦ã‚¦ã‚£ã‚¸ã‚§ãƒƒãƒˆã®æ­£ã—ã„ã‚ªãƒ¼ãƒŠãƒ¼ã¨ã—ã¦ä½¿ç”¨
    APlayerController* OwningPlayer = GetOwningPlayer();
    if (!OwningPlayer)
    {
        UE_LOG(LogTemp, Error, TEXT("UC_TeamCard::ShowTeamTaskMakeSheet - No owning player controller"));
        return;
    }
    
    // æ­£ã—ã„ã‚ªãƒ¼ãƒŠãƒ¼ï¼ˆPlayerControllerï¼‰ã§ã‚¦ã‚£ã‚¸ã‚§ãƒƒãƒˆã‚’ä½œæˆ
    UC_TeamTaskMakeSheet* TaskMakeSheet = CreateWidget<UC_TeamTaskMakeSheet>(OwningPlayer, TeamTaskMakeSheetClass);
    if (TaskMakeSheet)
    {
        UE_LOG(LogTemp, VeryVerbose, TEXT("UC_TeamCard::ShowTeamTaskMakeSheet - Widget created successfully"));
        
        // ãƒãƒ¼ãƒ æƒ…å ±ã§åˆæœŸåŒ–
        TaskMakeSheet->InitializeWithTeam(TeamIndex, TeamComponent);
        UE_LOG(LogTemp, VeryVerbose, TEXT("UC_TeamCard::ShowTeamTaskMakeSheet - Widget initialized"));
        
        // ç”»é¢ã«è¡¨ç¤º
        TaskMakeSheet->AddToViewport();
        
        // UIã‚¤ãƒ³ã‚¿ãƒ©ã‚¯ã‚·ãƒ§ãƒ³ç”¨ã®å…¥åŠ›ãƒ¢ãƒ¼ãƒ‰è¨­å®š
        OwningPlayer->SetInputMode(FInputModeGameAndUI());
        OwningPlayer->bShowMouseCursor = true;
        
        UE_LOG(LogTemp, VeryVerbose, TEXT("UC_TeamCard::ShowTeamTaskMakeSheet - TeamTaskMakeSheet added to viewport with input mode"));
    }
    else
    {
        UE_LOG(LogTemp, Error, TEXT("UC_TeamCard::ShowTeamTaskMakeSheet - Failed to create TaskMakeSheet widget"));
    }
}

// === æ¯ã‚¿ãƒ¼ãƒ³åˆ¤å®šç”¨ãƒ˜ãƒ«ãƒ‘ãƒ¼é–¢æ•° ===

FString UC_TeamCard::GetCurrentLocation() const
{
    // MovementComponentã‹ã‚‰ç¾åœ¨åœ°ã‚’å–å¾—
    if (UWorld* World = GetWorld())
    {
        if (APlayerController* PC = World->GetFirstPlayerController())
        {
            if (AC_PlayerController* IdlePC = Cast<AC_PlayerController>(PC))
            {
                if (ULocationMovementComponent* MovementComp = IdlePC->MovementComponent)
                {
                    float CurrentDistance = MovementComp->GetCurrentDistanceFromBase(TeamIndex);
                    
                    // è·é›¢ã‹ã‚‰å ´æ‰€ã‚’åˆ¤å®š
                    if (CurrentDistance <= 0.0f)
                    {
                        return TEXT("base");
                    }
                    else if (FMath::IsNearlyEqual(CurrentDistance, 100.0f, 5.0f))
                    {
                        return TEXT("plains");
                    }
                    else if (FMath::IsNearlyEqual(CurrentDistance, 200.0f, 5.0f))
                    {
                        return TEXT("forest");
                    }
                    else if (FMath::IsNearlyEqual(CurrentDistance, 500.0f, 5.0f))
                    {
                        return TEXT("swamp");
                    }
                    else if (FMath::IsNearlyEqual(CurrentDistance, 800.0f, 5.0f))
                    {
                        return TEXT("mountain");
                    }
                    else
                    {
                        // ç§»å‹•ä¸­ã®å ´åˆã¯æœ€å¯„ã‚Šã®å ´æ‰€ã‚’è¿”ã™
                        if (CurrentDistance < 50.0f) return TEXT("base");
                        else if (CurrentDistance < 150.0f) return TEXT("plains");
                        else if (CurrentDistance < 350.0f) return TEXT("forest");
                        else if (CurrentDistance < 650.0f) return TEXT("swamp");
                        else return TEXT("mountain");
                    }
                }
            }
        }
    }
    
    return TEXT("base"); // ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆ
}

FString UC_TeamCard::GetCurrentTargetItem() const
{
    // TaskManagerã‹ã‚‰å®Ÿè¡Œå¯èƒ½ã‚¿ã‚¹ã‚¯ã‚’å–å¾—
    if (UWorld* World = GetWorld())
    {
        if (APlayerController* PC = World->GetFirstPlayerController())
        {
            if (AC_PlayerController* IdlePC = Cast<AC_PlayerController>(PC))
            {
                if (UTaskManagerComponent* TaskManager = IdlePC->FindComponentByClass<UTaskManagerComponent>())
                {
                    FString CurrentLocation = GetCurrentLocation();
                    return TaskManager->GetTargetItemForTeam(TeamIndex, CurrentLocation);
                }
            }
        }
    }
    
    return FString(); // ã‚¿ã‚¹ã‚¯ãªã—
}

bool UC_TeamCard::IsTeamMoving() const
{
    // MovementComponentã‹ã‚‰ç§»å‹•çŠ¶æ…‹ã‚’ç¢ºèª
    if (UWorld* World = GetWorld())
    {
        if (APlayerController* PC = World->GetFirstPlayerController())
        {
            if (AC_PlayerController* IdlePC = Cast<AC_PlayerController>(PC))
            {
                if (ULocationMovementComponent* MovementComp = IdlePC->MovementComponent)
                {
                    EMovementState State = MovementComp->GetMovementState(TeamIndex);
                    
                    // ãƒ‡ãƒãƒƒã‚°ï¼šç§»å‹•çŠ¶æ…‹ã‚’ãƒ­ã‚°å‡ºåŠ›
                    UE_LOG(LogTemp, Warning, TEXT("ğŸ®ğŸ” TeamCard %d: MovementState = %d"), 
                        TeamIndex, (int32)State);
                    
                    return (State == EMovementState::MovingToDestination || State == EMovementState::MovingToBase);
                }
            }
        }
    }
    
    return false;
}

bool UC_TeamCard::ShouldUnloadItems() const
{
    // ãƒãƒ¼ãƒ ãƒ¡ãƒ³ãƒãƒ¼ãŒResourceã‚«ãƒ†ã‚´ãƒªã‚¢ã‚¤ãƒ†ãƒ ã‚’æŒã£ã¦ã„ã‚‹ã‹ãƒã‚§ãƒƒã‚¯
    if (!IsValidTeamCard())
    {
        return false;
    }
    
    FTeam TeamData = GetTeamData();
    
    for (AC_IdleCharacter* Member : TeamData.Members)
    {
        if (IsValid(Member))
        {
            if (UInventoryComponent* MemberInventory = Member->GetInventoryComponent())
            {
                // ã‚¤ãƒ³ãƒ™ãƒ³ãƒˆãƒªã«Resourceã‚«ãƒ†ã‚´ãƒªã®ã‚¢ã‚¤ãƒ†ãƒ ãŒã‚ã‚‹ã‹ãƒã‚§ãƒƒã‚¯
                // ç°¡æ˜“åˆ¤å®šï¼šwood, stone, ironãªã©ã®åŸºæœ¬è³‡æºãŒã‚ã‚‹ã‹ãƒã‚§ãƒƒã‚¯
                TArray<FString> ResourceItems = {TEXT("wood"), TEXT("stone"), TEXT("iron"), TEXT("food"), TEXT("ingredient")};
                
                for (const FString& ResourceItem : ResourceItems)
                {
                    if (MemberInventory->GetItemCount(ResourceItem) > 0)
                    {
                        return true;
                    }
                }
            }
        }
    }
    
    return false;
}

FString UC_TeamCard::GetMovementStatusText(bool bReturning) const
{
    // ç§»å‹•ä¸­ã®æ®‹ã‚Šæ™‚é–“ã‚’è¨ˆç®—
    if (UWorld* World = GetWorld())
    {
        if (APlayerController* PC = World->GetFirstPlayerController())
        {
            if (AC_PlayerController* IdlePC = Cast<AC_PlayerController>(PC))
            {
                if (ULocationMovementComponent* MovementComp = IdlePC->MovementComponent)
                {
                    float CurrentDistance = MovementComp->GetCurrentDistanceFromBase(TeamIndex);
                    int32 CurrentDistanceInt = FMath::RoundToInt(CurrentDistance);
                    
                    // ç›®æ¨™è·é›¢ã‚’å–å¾—
                    int32 TargetDistance = 0;
                    if (bReturning)
                    {
                        TargetDistance = 0; // æ‹ ç‚¹
                    }
                    else
                    {
                        // æ–°ã—ã„ã‚¿ã‚¹ã‚¯ã®ç›®çš„åœ°ã‚’å–å¾—
                        FTeam TeamData = GetTeamData();
                        FString GatheringLocationId = TeamData.GatheringLocationId;
                        
                        if (GatheringLocationId == TEXT("plains")) TargetDistance = 100;
                        else if (GatheringLocationId == TEXT("forest")) TargetDistance = 200;
                        else if (GatheringLocationId == TEXT("mountain")) TargetDistance = 800;
                        else if (GatheringLocationId == TEXT("swamp")) TargetDistance = 500;
                        else TargetDistance = 100; // ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆ
                    }
                    
                    int32 RemainingDistance = FMath::Abs(TargetDistance - CurrentDistanceInt);
                    
                    // MovementComponentã‹ã‚‰å®Ÿéš›ã®ç§»å‹•æƒ…å ±ã‚’å–å¾—
                    FMovementInfo MovementInfo = MovementComp->GetMovementInfo(TeamIndex);
                    
                    // State ã§ç§»å‹•ä¸­ã‹ãƒã‚§ãƒƒã‚¯
                    if (MovementInfo.State == EMovementState::MovingToDestination || 
                        MovementInfo.State == EMovementState::MovingToBase)
                    {
                        // å®Ÿéš›ã®æ®‹ã‚Šæ™‚é–“ã‚’ä½¿ç”¨
                        int32 RemainingSeconds = FMath::CeilToInt(MovementInfo.RemainingTime);
                        int32 Minutes = RemainingSeconds / 60;
                        int32 Seconds = RemainingSeconds % 60;
                        
                        FString TimeText = FString::Printf(TEXT("%02dï¼š%02d"), Minutes, Seconds);
                        FString MovementText = bReturning ? TEXT("å¸°é‚„") : TEXT("ç§»å‹•");
                        
                        UE_LOG(LogTemp, Warning, TEXT("ğŸ®â±ï¸ TeamCard %d: Actual remaining time = %.1fs (displayed as %s)"), 
                            TeamIndex, MovementInfo.RemainingTime, *TimeText);
                        
                        return FString::Printf(TEXT("%sï¼ˆæ®‹ã‚Š%sï¼‰"), *MovementText, *TimeText);
                    }
                    else if (RemainingDistance > 0)
                    {
                        // ãƒ•ã‚©ãƒ¼ãƒ«ãƒãƒƒã‚¯ï¼šç°¡æ˜“è¨ˆç®—
                        int32 MovementSpeed = 30;
                        int32 RemainingTurns = FMath::CeilToInt(static_cast<float>(RemainingDistance) / MovementSpeed);
                        int32 RemainingSeconds = RemainingTurns;
                        
                        int32 Minutes = RemainingSeconds / 60;
                        int32 Seconds = RemainingSeconds % 60;
                        
                        FString TimeText = FString::Printf(TEXT("%02dï¼š%02d"), Minutes, Seconds);
                        FString MovementText = bReturning ? TEXT("å¸°é‚„") : TEXT("ç§»å‹•");
                        
                        return FString::Printf(TEXT("%sï¼ˆæ®‹ã‚Š%sï¼‰"), *MovementText, *TimeText);
                    }
                    else
                    {
                        return bReturning ? TEXT("å¸°é‚„") : TEXT("ç§»å‹•");
                    }
                }
            }
        }
    }
    
    return bReturning ? TEXT("å¸°é‚„ä¸­") : TEXT("ç§»å‹•ä¸­");
}