// Fill out your copyright notice in the Description page of Project Settings.


#include "C_IdleCharacter.h"
#include "../Components/CharacterStatusComponent.h"
#include "../Components/InventoryComponent.h"
#include "../Components/CharacterBrain.h"
#include "../Components/LocationMovementComponent.h"
#include "../Components/TaskManagerComponent.h"
#include "../Components/TeamComponent.h"
#include "../C_PlayerController.h"
#include "Engine/World.h"
#include "Kismet/GameplayStatics.h"
#include "GameFramework/PawnMovementComponent.h"
#include "Components/StaticMeshComponent.h"
#include "Engine/StaticMesh.h"
#include "../AI/IdleAIController.h"

// Sets default values
AC_IdleCharacter::AC_IdleCharacter()
{
 	// Set this pawn to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;
	
	// APawnåŸºæœ¬è¨­å®š
	bUseControllerRotationYaw = false;
	bUseControllerRotationPitch = false;
	bUseControllerRotationRoll = false;
	
	// === UEæ¨™æº–ã‚³ãƒ³ãƒãƒ¼ãƒãƒ³ãƒˆã®ä½œæˆ ===
	
	// ç§»å‹•ã‚³ãƒ³ãƒãƒ¼ãƒãƒ³ãƒˆï¼ˆ2Dç”¨ï¼‰- åŸºæœ¬ã‚¯ãƒ©ã‚¹ã‚’ä½¿ç”¨
	FloatingMovement = CreateDefaultSubobject<UPawnMovementComponent>(TEXT("FloatingMovement"));
	if (FloatingMovement)
	{
		UE_LOG(LogTemp, VeryVerbose, TEXT("PawnMovementComponent created successfully"));
	}
	else
	{
		UE_LOG(LogTemp, Error, TEXT("Failed to create PawnMovementComponent"));
	}
	
	// 2Dè¡¨ç¤ºãƒ¡ãƒƒã‚·ãƒ¥
	IconMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("IconMesh"));
	if (IconMesh)
	{
		// ãƒ«ãƒ¼ãƒˆã‚³ãƒ³ãƒãƒ¼ãƒãƒ³ãƒˆã«è¨­å®š
		RootComponent = IconMesh;
		
		// ã‚·ãƒ³ãƒ—ãƒ«ãªçƒãƒ¡ãƒƒã‚·ãƒ¥ã‚’ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã¨ã—ã¦ä½¿ç”¨
		// ãƒ¡ãƒƒã‚·ãƒ¥ã¯å¾Œã§Blueprintã§è¨­å®šã™ã‚‹
		IconMesh->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);
		IconMesh->SetCollisionResponseToAllChannels(ECR_Block);
		IconMesh->SetCollisionResponseToChannel(ECC_Pawn, ECR_Block);
		
		UE_LOG(LogTemp, VeryVerbose, TEXT("IconMesh created successfully"));
	}
	else
	{
		UE_LOG(LogTemp, Error, TEXT("Failed to create IconMesh"));
	}
	
	// ã‚°ãƒªãƒƒãƒ‰ä½ç½®åˆæœŸåŒ–
	CurrentGridPosition = FIntPoint(10, 10); // ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆä½ç½®
	TargetGridPosition = CurrentGridPosition;
	
	// === AIã‚³ãƒ³ãƒˆãƒ­ãƒ¼ãƒ©ãƒ¼è¨­å®š ===
	AIControllerClass = AIdleAIController::StaticClass();
	AutoPossessAI = EAutoPossessAI::PlacedInWorldOrSpawned;
	
	UE_LOG(LogTemp, Warning, TEXT("AC_IdleCharacter: APawn constructor completed"));

	// ã‚³ãƒ³ãƒãƒ¼ãƒãƒ³ãƒˆä½œæˆï¼ˆé˜²å¾¡çš„ãƒã‚§ãƒƒã‚¯ä»˜ãï¼‰
	StatusComponent = CreateDefaultSubobject<UCharacterStatusComponent>(TEXT("StatusComponent"));
	if (!StatusComponent)
	{
		UE_LOG(LogTemp, Error, TEXT("Failed to create StatusComponent"));
	}
	else
	{
		UE_LOG(LogTemp, VeryVerbose, TEXT("StatusComponent created successfully"));
	}
	
	InventoryComponent = CreateDefaultSubobject<UInventoryComponent>(TEXT("InventoryComponent"));
	if (InventoryComponent)
	{
		// Set owner ID for character inventory
		InventoryComponent->OwnerId = TEXT("Character");
		UE_LOG(LogTemp, VeryVerbose, TEXT("InventoryComponent created successfully"));
	}
	else
	{
		UE_LOG(LogTemp, Error, TEXT("Failed to create InventoryComponent"));
	}

	// ===========================================
	// è‡ªå¾‹çš„ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã‚·ã‚¹ãƒ†ãƒ ã®åˆæœŸåŒ–
	// ===========================================
	
	// CharacterBrainã‚’ä½œæˆ
	MyBrain = CreateDefaultSubobject<UCharacterBrain>(TEXT("CharacterBrain"));
	if (!MyBrain)
	{
		UE_LOG(LogTemp, Error, TEXT("Failed to create CharacterBrain"));
	}
	else
	{
		UE_LOG(LogTemp, VeryVerbose, TEXT("CharacterBrain created successfully"));
	}

	// ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆè¨­å®š
	MyPersonality = ECharacterPersonality::Loyal; // ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã¯å¿ å®Ÿ
	bAutonomousSystemEnabled = true; // è‡ªå¾‹ã‚·ã‚¹ãƒ†ãƒ ã‚’æœ‰åŠ¹ã«ã™ã‚‹
	bShowDebugInfo = false; // ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã§ã¯ãƒ‡ãƒãƒƒã‚°æƒ…å ±ã¯éè¡¨ç¤º
	
	// åˆæœŸçŠ¶æ³ã¨ã‚¢ã‚¯ã‚·ãƒ§ãƒ³ã®è¨­å®š
	CurrentSituation = FCharacterSituation();
	PlannedAction = FCharacterAction();
}

// Called when the game starts or when spawned
void AC_IdleCharacter::BeginPlay()
{
	Super::BeginPlay();
	
	// ãƒ‡ãƒãƒƒã‚°ãƒ­ã‚°è¿½åŠ 
	UE_LOG(LogTemp, Warning, TEXT("C_IdleCharacter::BeginPlay - %s, InventoryComponent: %s"), 
		*GetName(), InventoryComponent ? TEXT("Valid") : TEXT("NULL"));
	
	// ã‚¤ãƒ³ãƒ™ãƒ³ãƒˆãƒªã®è£…å‚™å¤‰æ›´ã‚¤ãƒ™ãƒ³ãƒˆã‚’ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ã‚³ãƒ³ãƒãƒ¼ãƒãƒ³ãƒˆã®å†è¨ˆç®—ã«æ¥ç¶š
	if (InventoryComponent && StatusComponent)
	{
		UE_LOG(LogTemp, Warning, TEXT("C_IdleCharacter: Binding equipment change events"));
		
		// Dynamic multicast delegatesã¯AddDynamicã‚’ä½¿ç”¨
		InventoryComponent->OnItemEquipped.AddDynamic(this, &AC_IdleCharacter::HandleItemEquipped);
		InventoryComponent->OnItemUnequipped.AddDynamic(this, &AC_IdleCharacter::HandleItemUnequipped);
	}
	else
	{
		UE_LOG(LogTemp, Error, TEXT("C_IdleCharacter: Failed to bind equipment events - missing components"));
	}

	// ===========================================
	// è‡ªå¾‹çš„ã‚·ã‚¹ãƒ†ãƒ ã®åˆæœŸåŒ–
	// ===========================================
	
	if (bAutonomousSystemEnabled && MyBrain)
	{
		// CharacterBrainã«å¿…è¦ãªå‚ç…§ã‚’è¨­å®š
		AC_PlayerController* PlayerController = Cast<AC_PlayerController>(
			UGameplayStatics::GetPlayerController(GetWorld(), 0));
		
		if (PlayerController)
		{
			UTaskManagerComponent* TaskManager = PlayerController->FindComponentByClass<UTaskManagerComponent>();
			UTeamComponent* TeamComp = PlayerController->FindComponentByClass<UTeamComponent>();
			ULocationMovementComponent* MovementComp = PlayerController->FindComponentByClass<ULocationMovementComponent>();
			
			if (TaskManager && TeamComp && MovementComp)
			{
				MyBrain->SetCharacterReference(this);
				MyBrain->InitializeReferences(TaskManager, TeamComp, MovementComp);
				MyBrain->SetPersonality(MyPersonality);
				
				UE_LOG(LogTemp, Warning, TEXT("ğŸ§  Autonomous system initialized for character %s"), *CharacterName);
			}
			else
			{
				UE_LOG(LogTemp, Warning, TEXT("ğŸ§ âš ï¸ Failed to initialize autonomous system - missing components"));
			}
		}
	}
}

// Called every frame
void AC_IdleCharacter::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

// Equipment change handlers
void AC_IdleCharacter::HandleItemEquipped(const FString& ItemId, EEquipmentSlot Slot)
{
	UE_LOG(LogTemp, Warning, TEXT("C_IdleCharacter: Item equipped - %s in slot %d"), *ItemId, (int32)Slot);
	if (StatusComponent)
	{
		StatusComponent->OnEquipmentChanged();
	}
}

void AC_IdleCharacter::HandleItemUnequipped(const FString& ItemId, EEquipmentSlot Slot)
{
	UE_LOG(LogTemp, Warning, TEXT("C_IdleCharacter: Item unequipped - %s from slot %d"), *ItemId, (int32)Slot);
	if (StatusComponent)
	{
		StatusComponent->OnEquipmentChanged();
	}
}

// IIdleCharacterInterface Implementation
FString AC_IdleCharacter::GetCharacterName_Implementation()
{
	return CharacterName;
}



bool AC_IdleCharacter::IsActive_Implementation()
{
	return bIsActive;
}

UCharacterStatusComponent* AC_IdleCharacter::GetStatusComponent() const
{
	if (!StatusComponent)
	{
		UE_LOG(LogTemp, Error, TEXT("GetStatusComponent: StatusComponent is null for character %s"), 
			   CharacterName.IsEmpty() ? TEXT("Unknown") : *CharacterName);
		return nullptr;
	}
	else if (!IsValid(StatusComponent))
	{
		UE_LOG(LogTemp, Error, TEXT("GetStatusComponent: StatusComponent is invalid for character %s"), 
			   CharacterName.IsEmpty() ? TEXT("Unknown") : *CharacterName);
		return nullptr;
	}
	return StatusComponent;
}

UCharacterStatusComponent* AC_IdleCharacter::GetCharacterStatusComponent_Implementation()
{
	return GetStatusComponent();  // å®‰å…¨ãªGetStatusComponent()ã‚’ä½¿ç”¨
}

UInventoryComponent* AC_IdleCharacter::GetInventoryComponent() const
{
	// è©³ç´°ãªãƒ‡ãƒãƒƒã‚°ãƒ­ã‚°
	if (!InventoryComponent)
	{
		UE_LOG(LogTemp, VeryVerbose, TEXT("AC_IdleCharacter::GetInventoryComponent - InventoryComponent is NULL for %s"), *GetName());
		
		// const_castã‚’ä½¿ã£ã¦ã€FindComponentByClassã‚’è©¦ã™ï¼ˆãƒ‡ãƒãƒƒã‚°ç”¨ï¼‰
		AC_IdleCharacter* MutableThis = const_cast<AC_IdleCharacter*>(this);
		UInventoryComponent* FoundComp = MutableThis->FindComponentByClass<UInventoryComponent>();
		if (FoundComp)
		{
			UE_LOG(LogTemp, VeryVerbose, TEXT("AC_IdleCharacter::GetInventoryComponent - Found via FindComponentByClass"));
			return FoundComp;
		}
	}
	
	return InventoryComponent;
}

UInventoryComponent* AC_IdleCharacter::GetCharacterInventoryComponent_Implementation()
{
	return InventoryComponent;
}

FCharacterTalent AC_IdleCharacter::GetCharacterTalent_Implementation()
{
	if (StatusComponent)
	{
		return StatusComponent->GetTalent();
	}
	return FCharacterTalent();
}

FDerivedStats AC_IdleCharacter::GetDerivedStats() const
{
	if (StatusComponent)
	{
		return StatusComponent->GetDerivedStats();
	}
	return FDerivedStats();
}

// ===========================================
// è‡ªå¾‹çš„ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã‚·ã‚¹ãƒ†ãƒ ã®å®Ÿè£…
// ===========================================

void AC_IdleCharacter::OnTurnTick(int32 CurrentTurn)
{
	// æ–°ã—ã„Behavior Treeè‡ªå¾‹ã‚·ã‚¹ãƒ†ãƒ ã§ã®å®Ÿè£…
	UE_LOG(LogTemp, Warning, TEXT("ğŸ§  %s: OnTurnTick(Turn %d) - Behavior Tree autonomous processing"), 
		*CharacterName, CurrentTurn);

	// AIControllerã‹ã‚‰Behavior Treeã‚’å†é–‹ï¼ˆæ¯ã‚¿ãƒ¼ãƒ³æ–°ã—ã„åˆ¤æ–­ï¼‰
	if (auto* AIController = GetController<AIdleAIController>())
	{
		AIController->RestartBehaviorTree();
		UE_LOG(LogTemp, Warning, TEXT("ğŸ§ ğŸ”„ %s: Behavior Tree restarted for fresh decision"), 
			*CharacterName);
	}
	else
	{
		// ãƒ•ã‚©ãƒ¼ãƒ«ãƒãƒƒã‚¯ï¼šæ—§ã‚·ã‚¹ãƒ†ãƒ ãŒæ®‹ã£ã¦ã„ã‚‹å ´åˆ
		if (bAutonomousSystemEnabled && MyBrain)
		{
			UE_LOG(LogTemp, Warning, TEXT("ğŸ§ âš ï¸ %s: Using fallback CharacterBrain system"), *CharacterName);
			
			// è‡ªå¾‹çš„ãªåˆ¤æ–­ãƒ—ãƒ­ã‚»ã‚¹ã‚’å®Ÿè¡Œ
			AnalyzeMySituation();
			ConsultMyTeam();
			DecideMyAction();
			ExecuteMyAction();

			// ãƒ‡ãƒãƒƒã‚°æƒ…å ±è¡¨ç¤º
			if (bShowDebugInfo)
			{
				UE_LOG(LogTemp, Warning, TEXT("ğŸ§ ğŸ“Š %s: Decided action %d (%s)"), 
					*CharacterName, 
					(int32)PlannedAction.ActionType, 
					*PlannedAction.ActionReason);
			}
		}
	}
}

void AC_IdleCharacter::SetPersonality(ECharacterPersonality NewPersonality)
{
	MyPersonality = NewPersonality;
	
	if (MyBrain)
	{
		MyBrain->SetPersonality(NewPersonality);
	}
	
	UE_LOG(LogTemp, Log, TEXT("ğŸ§  %s: Personality set to %d"), 
		*CharacterName, (int32)NewPersonality);
}

void AC_IdleCharacter::AnalyzeMySituation()
{
	UE_LOG(LogTemp, VeryVerbose, TEXT("ğŸ§ ğŸ” %s: Starting situation analysis"), *CharacterName);
	
	// ç¾åœ¨åœ°ã®å–å¾—ï¼ˆLocationMovementComponentã‹ã‚‰ç›´æ¥ï¼‰
	// GetCurrentLocationDirect()ãŒå­˜åœ¨ã—ãªã„ãŸã‚ä¸€æ™‚çš„ã«"base"ã«è¨­å®š
	CurrentSituation.CurrentLocation = TEXT("base");

	// ä½“åŠ›ãƒ»ã‚¹ã‚¿ãƒŸãƒŠã®å–å¾—
	if (StatusComponent)
	{
		FCharacterStatus Status = StatusComponent->GetStatus();
		CurrentSituation.CurrentHealth = Status.CurrentHealth;
		CurrentSituation.CurrentStamina = Status.CurrentStamina;
	}

	// ãƒãƒ¼ãƒ æƒ…å ±ã®å–å¾—
	AC_PlayerController* PlayerController = Cast<AC_PlayerController>(
		UGameplayStatics::GetPlayerController(GetWorld(), 0));
	
	if (PlayerController)
	{
		UTeamComponent* TeamComp = PlayerController->FindComponentByClass<UTeamComponent>();
		if (TeamComp)
		{
			// æ‰€å±ãƒãƒ¼ãƒ ã‚’æ¤œç´¢
			CurrentSituation.MyTeamIndex = -1;
			for (int32 i = 0; i < TeamComp->GetTeamCount(); i++)
			{
				FTeam Team = TeamComp->GetTeam(i);
				if (Team.Members.Contains(this))
				{
					CurrentSituation.MyTeamIndex = i;
					CurrentSituation.TeamAssignedTask = Team.AssignedTask;
					CurrentSituation.Teammates = Team.Members;
					
					UE_LOG(LogTemp, VeryVerbose, TEXT("ğŸ§ ğŸ‘¥ %s: Found in Team %d, assigned task: %d"), 
						*CharacterName, i, (int32)Team.AssignedTask);
					break;
				}
			}
			
			if (CurrentSituation.MyTeamIndex == -1)
			{
				UE_LOG(LogTemp, Warning, TEXT("ğŸ§ âš ï¸ %s: Not assigned to any team!"), *CharacterName);
			}
		}
		else
		{
			UE_LOG(LogTemp, Warning, TEXT("ğŸ§ âš ï¸ %s: TeamComponent not found!"), *CharacterName);
		}
	}
	else
	{
		UE_LOG(LogTemp, Warning, TEXT("ğŸ§ âš ï¸ %s: PlayerController not found!"), *CharacterName);
	}

	// åˆ©ç”¨å¯èƒ½ã‚¿ã‚¹ã‚¯ã®å–å¾—ï¼ˆTaskInformationServiceå‰Šé™¤ã«ã‚ˆã‚Šä¸€æ™‚çš„ã«ç„¡åŠ¹åŒ–ï¼‰
	// å¿…è¦ã«å¿œã˜ã¦åˆ¥ã®æ–¹æ³•ã§å®Ÿè£…
	CurrentSituation.AvailableTasks.Empty();

	// æ¡é›†å¯èƒ½ã‚¢ã‚¤ãƒ†ãƒ ã®å–å¾—ï¼ˆTaskManagerã«ç§»è¡Œï¼‰
	AC_PlayerController* PC = Cast<AC_PlayerController>(UGameplayStatics::GetPlayerController(GetWorld(), 0));
	if (PC)
	{
		if (UTaskManagerComponent* TaskManager = PC->FindComponentByClass<UTaskManagerComponent>())
		{
			CurrentSituation.GatherableItems = TaskManager->GetGatherableItemsAt(CurrentSituation.CurrentLocation);
		}
	}

	// å±é™ºåœ°åŸŸåˆ¤å®šï¼ˆç°¡æ˜“ç‰ˆï¼‰
	CurrentSituation.bDangerousArea = (CurrentSituation.CurrentLocation != TEXT("base"));

	UE_LOG(LogTemp, VeryVerbose, TEXT("ğŸ§ ğŸ” %s: Situation analyzed - Location: %s, Team: %d, Task: %d"), 
		*CharacterName, 
		*CurrentSituation.CurrentLocation, 
		CurrentSituation.MyTeamIndex, 
		(int32)CurrentSituation.TeamAssignedTask);
}

void AC_IdleCharacter::ConsultMyTeam()
{
	// Phase 2.3: ãƒãƒ¼ãƒ é€£æºæ©Ÿèƒ½ã®å¼·åŒ–å®Ÿè£…
	// TeamComponentã®æ–°ã—ã„é€£æºæ©Ÿèƒ½ã‚’æ´»ç”¨
	
	if (CurrentSituation.MyTeamIndex == -1)
	{
		UE_LOG(LogTemp, VeryVerbose, TEXT("ğŸ§ ğŸ‘¥ %s: Not in any team, skipping team consultation"), *CharacterName);
		return;
	}

	// PlayerControllerã‹ã‚‰TeamComponentã‚’å–å¾—
	AC_PlayerController* PlayerController = Cast<AC_PlayerController>(
		UGameplayStatics::GetPlayerController(GetWorld(), 0));
		
	if (!PlayerController)
	{
		UE_LOG(LogTemp, Warning, TEXT("ğŸ§ ğŸ‘¥âš ï¸ %s: PlayerController not found"), *CharacterName);
		return;
	}

	UTeamComponent* TeamComp = PlayerController->FindComponentByClass<UTeamComponent>();
	if (!TeamComp)
	{
		UE_LOG(LogTemp, Warning, TEXT("ğŸ§ ğŸ‘¥âš ï¸ %s: TeamComponent not found"), *CharacterName);
		return;
	}

	// ========================================
	// 1. ãƒãƒ¼ãƒ æˆ¦ç•¥ã®å–å¾—ã¨åˆ†æ
	// ========================================
	
	FTeamStrategy TeamStrategy = TeamComp->GetTeamStrategy(CurrentSituation.MyTeamIndex);
	
	// å–å¾—ã—ãŸæˆ¦ç•¥ã‚’çŠ¶æ³ã«åæ˜ 
	CurrentSituation.RecommendedTaskType = TeamStrategy.RecommendedTaskType;
	CurrentSituation.TeamRecommendedLocation = TeamStrategy.RecommendedLocation;
	CurrentSituation.TeamRecommendedItem = TeamStrategy.RecommendedTargetItem;
	CurrentSituation.TeamStrategyReason = TeamStrategy.StrategyReason;
	
	UE_LOG(LogTemp, Verbose, TEXT("ğŸ§ ğŸ‘¥ğŸ“‹ %s: Team strategy - Task: %d, Location: %s, Item: %s"), 
		*CharacterName, 
		(int32)TeamStrategy.RecommendedTaskType,
		*TeamStrategy.RecommendedLocation,
		*TeamStrategy.RecommendedTargetItem);

	// ========================================
	// 2. è©³ç´°ãªãƒãƒ¼ãƒ æƒ…å ±ã®å–å¾—
	// ========================================
	
	FTeamInfo DetailedTeamInfo = TeamComp->GetTeamInfoForCharacter(this);
	
	// ãƒãƒ¼ãƒ æƒ…å ±ã‚’çŠ¶æ³ã«åæ˜ 
	CurrentSituation.TeamActionState = DetailedTeamInfo.ActionState;
	CurrentSituation.ActiveTeammates = DetailedTeamInfo.ActiveMembers;
	CurrentSituation.TotalTeammates = DetailedTeamInfo.TotalMembers;
	CurrentSituation.CurrentTeamTarget = DetailedTeamInfo.CurrentTargetLocation;
	CurrentSituation.bTeamNeedsCoordination = DetailedTeamInfo.bNeedsCoordination;
	CurrentSituation.TeamCoordinationMessage = DetailedTeamInfo.CoordinationMessage;
	
	UE_LOG(LogTemp, Verbose, TEXT("ğŸ§ ğŸ‘¥ğŸ“Š %s: Team info - Members: %d/%d, State: %d, Target: %s"), 
		*CharacterName, 
		DetailedTeamInfo.ActiveMembers,
		DetailedTeamInfo.TotalMembers,
		(int32)DetailedTeamInfo.ActionState,
		*DetailedTeamInfo.CurrentTargetLocation);

	// ========================================
	// 3. ãƒãƒ¼ãƒ é€£æºãŒå¿…è¦ãªå ´åˆã®å‡¦ç†
	// ========================================
	
	if (CurrentSituation.bTeamNeedsCoordination)
	{
		UE_LOG(LogTemp, Log, TEXT("ğŸ§ ğŸ‘¥ğŸ¤ %s: Team coordination needed - %s"), 
			*CharacterName, 
			*CurrentSituation.TeamCoordinationMessage);
			
		// é€£æºãŒå¿…è¦ãªå ´åˆã¯ã€å¾Œã§DecideMyAction()ã§ã®è¡Œå‹•æ±ºå®šæ™‚ã«
		// CoordinateWithTeammates()ã‚’å‘¼ã³å‡ºã™ãƒ•ãƒ©ã‚°ã‚’è¨­å®š
		CurrentSituation.bShouldCoordinateAction = true;
	}
	else
	{
		CurrentSituation.bShouldCoordinateAction = false;
	}

	// ========================================
	// 4. ãƒãƒ¼ãƒ çŠ¶æ³ã®ç·åˆåˆ¤æ–­
	// ========================================
	
	// ãƒãƒ¼ãƒ ã®åŠ¹ç‡æ€§ã‚’åˆ¤æ–­
	float TeamEfficiency = (float)DetailedTeamInfo.ActiveMembers / (float)FMath::Max(1, DetailedTeamInfo.TotalMembers);
	CurrentSituation.TeamEfficiency = TeamEfficiency;
	
	// ãƒãƒ¼ãƒ æˆ¦ç•¥ã®å„ªå…ˆåº¦ã‚’è€ƒæ…®
	CurrentSituation.bShouldFollowTeamStrategy = (TeamStrategy.StrategyPriority >= 3); // å„ªå…ˆåº¦3ä»¥ä¸Šãªã‚‰å¾“ã†
	
	// æ€§æ ¼ã«åŸºã¥ãå”èª¿æ€§ã®åˆ¤å®š
	bool bPersonalitySupportsTeamwork = (MyPersonality == ECharacterPersonality::Loyal || 
	                                   MyPersonality == ECharacterPersonality::Defensive);
	CurrentSituation.bPersonallyCooperative = bPersonalitySupportsTeamwork;

	UE_LOG(LogTemp, VeryVerbose, TEXT("ğŸ§ ğŸ‘¥âœ… %s: Team consultation completed - Strategy priority: %d, Should coordinate: %s, Team efficiency: %.2f"), 
		*CharacterName, 
		TeamStrategy.StrategyPriority,
		CurrentSituation.bShouldCoordinateAction ? TEXT("Yes") : TEXT("No"),
		TeamEfficiency);
}

void AC_IdleCharacter::DecideMyAction()
{
	if (!MyBrain)
	{
		UE_LOG(LogTemp, Error, TEXT("ğŸ§ âŒ %s: MyBrain is null - using default wait action"), *CharacterName);
		PlannedAction = FCharacterAction(); // ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã‚¢ã‚¯ã‚·ãƒ§ãƒ³ï¼ˆå¾…æ©Ÿï¼‰
		PlannedAction.ActionReason = TEXT("No brain available");
		return;
	}
	
	UE_LOG(LogTemp, VeryVerbose, TEXT("ğŸ§ ğŸ¯ %s: Brain available, analyzing situation for decision"), *CharacterName);

	// ========================================
	// Phase 2.3: ãƒãƒ¼ãƒ é€£æºã‚’è€ƒæ…®ã—ãŸè¡Œå‹•æ±ºå®š
	// ========================================

	// 1. CharacterBrainã«åŸºæœ¬çš„ãªåˆ¤æ–­ã‚’å§”è­²
	FCharacterAction InitialAction = MyBrain->DecideOptimalAction(CurrentSituation);
	
	UE_LOG(LogTemp, VeryVerbose, TEXT("ğŸ§ ğŸ¯ %s: Initial action decided - %d (%s)"), 
		*CharacterName, 
		(int32)InitialAction.ActionType, 
		*InitialAction.ActionReason);

	// 2. ãƒãƒ¼ãƒ é€£æºãŒå¿…è¦ãªå ´åˆã®èª¿æ•´å‡¦ç†
	if (CurrentSituation.bShouldCoordinateAction && CurrentSituation.MyTeamIndex != -1)
	{
		// PlayerControllerã‹ã‚‰TeamComponentã‚’å–å¾—
		AC_PlayerController* PlayerController = Cast<AC_PlayerController>(
			UGameplayStatics::GetPlayerController(GetWorld(), 0));
			
		if (PlayerController)
		{
			UTeamComponent* TeamComp = PlayerController->FindComponentByClass<UTeamComponent>();
			if (TeamComp)
			{
				// ãƒãƒ¼ãƒ ãƒ¡ãƒ³ãƒãƒ¼ã¨ã®è¡Œå‹•èª¿æ•´ã‚’å®Ÿè¡Œ
				bool bActionApproved = TeamComp->CoordinateWithTeammates(this, InitialAction);
				
				if (bActionApproved)
				{
					// è¡Œå‹•ãŒæ‰¿èªã•ã‚ŒãŸå ´åˆã¯ãã®ã¾ã¾æ¡ç”¨
					PlannedAction = InitialAction;
					PlannedAction.ActionReason += TEXT(" (Team coordinated)");
					
					UE_LOG(LogTemp, Verbose, TEXT("ğŸ§ ğŸ‘¥âœ… %s: Action approved by team coordination"), 
						*CharacterName);
				}
				else
				{
					// è¡Œå‹•ãŒèª¿æ•´ã•ã‚ŒãŸå ´åˆã¯ä»£æ›¿æ¡ˆã‚’æ¤œè¨
					UE_LOG(LogTemp, Verbose, TEXT("ğŸ§ ğŸ‘¥ğŸ”„ %s: Action adjustment needed by team"), 
						*CharacterName);
					
					// ä»£æ›¿è¡Œå‹•ã‚’æ±ºå®šï¼ˆãƒãƒ¼ãƒ æˆ¦ç•¥ã«åŸºã¥ãï¼‰
					FCharacterAction AdjustedAction = DetermineAdjustedAction();
					PlannedAction = AdjustedAction;
				}
			}
			else
			{
				// TeamComponentãŒè¦‹ã¤ã‹ã‚‰ãªã„å ´åˆã¯åˆæœŸè¡Œå‹•ã‚’ãã®ã¾ã¾ä½¿ç”¨
				PlannedAction = InitialAction;
				PlannedAction.ActionReason += TEXT(" (No team coordination available)");
			}
		}
		else
		{
			// PlayerControllerãŒè¦‹ã¤ã‹ã‚‰ãªã„å ´åˆ
			PlannedAction = InitialAction;
			PlannedAction.ActionReason += TEXT(" (No player controller)");
		}
	}
	else
	{
		// ãƒãƒ¼ãƒ é€£æºãŒä¸è¦ãªå ´åˆã¯åˆæœŸè¡Œå‹•ã‚’ãã®ã¾ã¾ä½¿ç”¨
		PlannedAction = InitialAction;
		
		// ãƒãƒ¼ãƒ æˆ¦ç•¥ã‚’å°Šé‡ã™ã¹ãå ´åˆã®è¿½åŠ åˆ¤å®š
		if (CurrentSituation.bShouldFollowTeamStrategy && 
		    CurrentSituation.bPersonallyCooperative)
		{
			// ãƒãƒ¼ãƒ æˆ¦ç•¥ã«æ²¿ã£ãŸè¡Œå‹•ã¸ã®èª¿æ•´ã‚’æ¤œè¨
			FCharacterAction StrategyAlignedAction = AlignActionWithTeamStrategy(InitialAction);
			if (StrategyAlignedAction.ActionType != ECharacterActionType::Wait)
			{
				PlannedAction = StrategyAlignedAction;
			}
		}
	}
	
	UE_LOG(LogTemp, VeryVerbose, TEXT("ğŸ§ ğŸ¯âœ… %s: Final action decided - %d (%s)"), 
		*CharacterName, 
		(int32)PlannedAction.ActionType, 
		*PlannedAction.ActionReason);
}

// ========================================
// Phase 2.3: ãƒãƒ¼ãƒ é€£æºç”¨ãƒ˜ãƒ«ãƒ‘ãƒ¼ãƒ¡ã‚½ãƒƒãƒ‰
// ========================================

FCharacterAction AC_IdleCharacter::DetermineAdjustedAction()
{
	// ãƒãƒ¼ãƒ èª¿æ•´ãŒå¿…è¦ãªå ´åˆã®ä»£æ›¿è¡Œå‹•æ±ºå®š
	FCharacterAction AdjustedAction;
	
	// ãƒãƒ¼ãƒ æˆ¦ç•¥ã«åŸºã¥ãè¡Œå‹•ã‚’å„ªå…ˆ
	if (CurrentSituation.RecommendedTaskType != ETaskType::Idle)
	{
		switch (CurrentSituation.RecommendedTaskType)
		{
			case ETaskType::Gathering:
				AdjustedAction.ActionType = ECharacterActionType::GatherResources;
				AdjustedAction.TargetItem = CurrentSituation.TeamRecommendedItem;
				AdjustedAction.TargetLocation = CurrentSituation.TeamRecommendedLocation;
				AdjustedAction.ActionReason = TEXT("Team strategy: Gathering");
				break;
				
			case ETaskType::Adventure:
				AdjustedAction.ActionType = ECharacterActionType::AttackEnemy;
				AdjustedAction.TargetLocation = CurrentSituation.TeamRecommendedLocation;
				AdjustedAction.ActionReason = TEXT("Team strategy: Adventure");
				break;
				
			default:
				// ãã®ä»–ã®ã‚¿ã‚¹ã‚¯ã‚¿ã‚¤ãƒ—ã®å ´åˆã¯å¾…æ©Ÿ
				AdjustedAction.ActionType = ECharacterActionType::Wait;
				AdjustedAction.ActionReason = TEXT("Team coordination: Waiting for assignment");
				break;
		}
	}
	else
	{
		// æ¨å¥¨ã‚¿ã‚¹ã‚¯ãŒãªã„å ´åˆã¯å¾…æ©Ÿ
		AdjustedAction.ActionType = ECharacterActionType::Wait;
		AdjustedAction.ActionReason = TEXT("Team coordination: No specific task assigned");
	}
	
	UE_LOG(LogTemp, Verbose, TEXT("ğŸ§ ğŸ‘¥ğŸ”„ %s: Adjusted action - %d (%s)"), 
		*CharacterName, 
		(int32)AdjustedAction.ActionType, 
		*AdjustedAction.ActionReason);
	
	return AdjustedAction;
}

FCharacterAction AC_IdleCharacter::AlignActionWithTeamStrategy(const FCharacterAction& OriginalAction)
{
	// å…ƒã®è¡Œå‹•ã‚’ãƒãƒ¼ãƒ æˆ¦ç•¥ã«åˆã‚ã›ã¦èª¿æ•´
	FCharacterAction AlignedAction = OriginalAction;
	
	// ãƒãƒ¼ãƒ æ¨å¥¨å ´æ‰€ãŒã‚ã‚‹å ´åˆã®èª¿æ•´
	if (!CurrentSituation.TeamRecommendedLocation.IsEmpty() && 
	    CurrentSituation.TeamRecommendedLocation != CurrentSituation.CurrentLocation)
	{
		// æ¨å¥¨å ´æ‰€ã¸ã®ç§»å‹•ã‚’å„ªå…ˆ
		if (OriginalAction.ActionType == ECharacterActionType::GatherResources ||
		    OriginalAction.ActionType == ECharacterActionType::AttackEnemy)
		{
			AlignedAction.TargetLocation = CurrentSituation.TeamRecommendedLocation;
			AlignedAction.ActionReason += TEXT(" (Aligned with team location)");
		}
	}
	
	// ãƒãƒ¼ãƒ æ¨å¥¨ã‚¢ã‚¤ãƒ†ãƒ ãŒã‚ã‚‹å ´åˆã®èª¿æ•´
	if (!CurrentSituation.TeamRecommendedItem.IsEmpty() && 
	    OriginalAction.ActionType == ECharacterActionType::GatherResources)
	{
		AlignedAction.TargetItem = CurrentSituation.TeamRecommendedItem;
		AlignedAction.ActionReason += TEXT(" (Aligned with team target item)");
	}
	
	UE_LOG(LogTemp, VeryVerbose, TEXT("ğŸ§ ğŸ‘¥ğŸ“‹ %s: Action aligned with team strategy"), *CharacterName);
	
	return AlignedAction;
}

void AC_IdleCharacter::ExecuteMyAction()
{
	if (PlannedAction.ActionType == ECharacterActionType::Wait)
	{
		// å¾…æ©Ÿã®å ´åˆã¯ä½•ã‚‚ã—ãªã„
		UE_LOG(LogTemp, VeryVerbose, TEXT("ğŸ§ ğŸ’¤ %s: Executing wait action"), *CharacterName);
		return;
	}

	// ğŸ”„ ç¶™ç¶šçš„ãªè¡Œå‹•ç®¡ç†ï¼šç§»å‹•ã‚„ä½œæ¥­ã®é€²è¡ŒçŠ¶æ³ã‚’ãƒã‚§ãƒƒã‚¯
	CheckAndUpdateActionProgress();

	// å„ç¨®ã‚µãƒ¼ãƒ“ã‚¹ã‚’é€šã˜ã¦è¡Œå‹•ã‚’å®Ÿè¡Œ
	switch (PlannedAction.ActionType)
	{
		case ECharacterActionType::MoveToLocation:
			ExecuteMovementAction();
			break;
			
		case ECharacterActionType::GatherResources:
			ExecuteGatheringAction();
			break;
			
		case ECharacterActionType::AttackEnemy:
			ExecuteCombatAction();
			break;
			
		case ECharacterActionType::ReturnToBase:
			ExecuteReturnAction();
			break;
			
		case ECharacterActionType::UnloadItems:
			ExecuteUnloadAction();
			break;
			
		default:
			UE_LOG(LogTemp, Warning, TEXT("ğŸ§ âš ï¸ %s: Unhandled action type %d"), 
				*CharacterName, (int32)PlannedAction.ActionType);
			break;
	}
}

void AC_IdleCharacter::CheckAndUpdateActionProgress()
{
	UE_LOG(LogTemp, VeryVerbose, TEXT("ğŸ§ ğŸ”„ %s: Checking action progress for %d"), 
		*CharacterName, (int32)PlannedAction.ActionType);
	
	// ç§»å‹•ã‚¢ã‚¯ã‚·ãƒ§ãƒ³ã®å ´åˆï¼šç§»å‹•å®Œäº†ã‚’ãƒã‚§ãƒƒã‚¯
	if (PlannedAction.ActionType == ECharacterActionType::MoveToLocation)
	{
		if (CurrentSituation.MyTeamIndex != -1)
		{
			bool bMovementCompleted = CheckMovementProgressDirect();
			if (bMovementCompleted)
			{
				UE_LOG(LogTemp, Warning, TEXT("ğŸ§ âœ… %s: Movement completed! Analyzing new situation..."), *CharacterName);
				
				// ç§»å‹•å®Œäº†ï¼šçŠ¶æ³ã‚’å†åˆ†æã—ã¦æ¬¡ã®è¡Œå‹•ã‚’æ±ºå®š
				AnalyzeMySituation();
				ConsultMyTeam(); 
				DecideMyAction();
				
				UE_LOG(LogTemp, Warning, TEXT("ğŸ§ ğŸ”„ %s: New action after movement: %d (%s)"), 
					*CharacterName, (int32)PlannedAction.ActionType, *PlannedAction.ActionReason);
			}
			else
			{
				UE_LOG(LogTemp, VeryVerbose, TEXT("ğŸ§ ğŸš¶ %s: Still moving... waiting for completion"), *CharacterName);
			}
		}
	}
	
	// è·ä¸‹ã‚ã—ã‚¢ã‚¯ã‚·ãƒ§ãƒ³ã®å ´åˆï¼šExecuteMyAction()ã§å®Ÿéš›ã«å®Ÿè¡Œã•ã‚Œã‚‹ãŸã‚ã€ã“ã“ã§ã¯ä½•ã‚‚ã—ãªã„
	// (å³åº§ã«å®Œäº†åˆ¤å®šã™ã‚‹ã¨ã€å®Ÿéš›ã®è·ä¸‹ã‚ã—å‰ã«æ¬¡ã®ã‚¢ã‚¯ã‚·ãƒ§ãƒ³ã‚’æ±ºå®šã—ã¦ã—ã¾ã„ç„¡é™ãƒ«ãƒ¼ãƒ—ã«ãªã‚‹)
	
	// æ¡é›†ã‚¢ã‚¯ã‚·ãƒ§ãƒ³ã®å ´åˆï¼šæ¡é›†å®Œäº†ã‚’ãƒã‚§ãƒƒã‚¯ï¼ˆå°†æ¥å®Ÿè£…ï¼‰
	// æˆ¦é—˜ã‚¢ã‚¯ã‚·ãƒ§ãƒ³ã®å ´åˆï¼šæˆ¦é—˜å®Œäº†ã‚’ãƒã‚§ãƒƒã‚¯ï¼ˆå°†æ¥å®Ÿè£…ï¼‰
}

void AC_IdleCharacter::ExecuteMovementAction()
{
	bool bSuccess = MoveToLocationDirect(PlannedAction.TargetLocation);
	
	UE_LOG(LogTemp, VeryVerbose, TEXT("ğŸ§ ğŸš¶ %s: Movement to %s %s"), 
		*CharacterName, 
		*PlannedAction.TargetLocation, 
		bSuccess ? TEXT("started") : TEXT("failed"));
}

void AC_IdleCharacter::ExecuteGatheringAction()
{
	// TaskManagerã«ç§»è¡Œæ¸ˆã¿ã®æ¡é›†å®Ÿè¡Œ
	AC_PlayerController* PC = Cast<AC_PlayerController>(UGameplayStatics::GetPlayerController(GetWorld(), 0));
	if (!PC)
	{
		UE_LOG(LogTemp, Error, TEXT("ğŸ§ âŒ %s: PlayerController not available"), *CharacterName);
		return;
	}
	
	UTaskManagerComponent* TaskManager = PC->FindComponentByClass<UTaskManagerComponent>();
	if (!TaskManager)
	{
		UE_LOG(LogTemp, Error, TEXT("ğŸ§ âŒ %s: TaskManager not available"), *CharacterName);
		return;
	}
	
	// ãƒãƒ¼ãƒ ã‚¤ãƒ³ãƒ‡ãƒƒã‚¯ã‚¹ã‚’å–å¾—
	UTeamComponent* TeamComp = PC->FindComponentByClass<UTeamComponent>();
	int32 MyTeamIndex = -1;
	if (TeamComp)
	{
		for (int32 i = 0; i < TeamComp->GetTeamCount(); i++)
		{
			FTeam Team = TeamComp->GetTeam(i);
			if (Team.Members.Contains(this))
			{
				MyTeamIndex = i;
				break;
			}
		}
	}
	
	if (MyTeamIndex == -1)
	{
		UE_LOG(LogTemp, Error, TEXT("ğŸ§ âŒ %s: Could not find team index"), *CharacterName);
		return;
	}
	
	// ç¾åœ¨åœ°ã‚’å–å¾—
	FString CurrentLocation = GetCurrentLocationDirect();
	
	bool bSuccess = TaskManager->ExecuteGathering(MyTeamIndex, PlannedAction.TargetItem, CurrentLocation);
	
	UE_LOG(LogTemp, VeryVerbose, TEXT("ğŸ§ â›ï¸ %s: Gathering %s %s"), 
		*CharacterName, 
		*PlannedAction.TargetItem, 
		bSuccess ? TEXT("started") : TEXT("failed"));
}

void AC_IdleCharacter::ExecuteCombatAction()
{
	// æˆ¦é—˜æ©Ÿèƒ½ã¯æœªå®Ÿè£…
	UE_LOG(LogTemp, Warning, TEXT("ğŸ§ âš”ï¸ %s: Combat action not yet implemented"), *CharacterName);
	bool bSuccess = false;
	
	UE_LOG(LogTemp, VeryVerbose, TEXT("ğŸ§ âš”ï¸ %s: Combat at %s %s"), 
		*CharacterName, 
		*PlannedAction.TargetLocation, 
		bSuccess ? TEXT("started") : TEXT("failed"));
}

void AC_IdleCharacter::ExecuteReturnAction()
{
	// æ‹ ç‚¹å¸°é‚„ã¯ç§»å‹•ã‚¢ã‚¯ã‚·ãƒ§ãƒ³ã¨åŒã˜
	FCharacterAction ReturnAction = PlannedAction;
	ReturnAction.ActionType = ECharacterActionType::MoveToLocation;
	ReturnAction.TargetLocation = TEXT("base");
	
	PlannedAction = ReturnAction;
	ExecuteMovementAction();
}

void AC_IdleCharacter::ExecuteUnloadAction()
{
	FString CharName = GetName();
	UE_LOG(LogTemp, Warning, TEXT("ğŸ§ ğŸ“¦ %s: Executing unload action"), *CharName);
	
	// PlayerControllerã‚’å–å¾—ã—ã¦è·ä¸‹ã‚ã—
	AC_PlayerController* PlayerController = Cast<AC_PlayerController>(
		UGameplayStatics::GetPlayerController(GetWorld(), 0));
	
	if (!PlayerController)
	{
		UE_LOG(LogTemp, Error, TEXT("ğŸ§ âŒ %s: PlayerController not found for unload"), *CharName);
		return;
	}
	
	UE_LOG(LogTemp, Warning, TEXT("ğŸ§ ğŸ“¦ %s: PlayerController found, checking inventory"), *CharName);
	
	// InventoryComponentã‚’å–å¾—ï¼ˆæ—¢å­˜ã®ãƒ¡ãƒ³ãƒå¤‰æ•°ã¨FindComponentã®ä¸¡æ–¹ã‚’è©¦ã™ï¼‰
	UInventoryComponent* MyInventory = InventoryComponent;
	if (!MyInventory)
	{
		UE_LOG(LogTemp, Warning, TEXT("ğŸ§ ğŸ“¦ %s: InventoryComponent member is null, trying FindComponentByClass"), *CharName);
		MyInventory = FindComponentByClass<UInventoryComponent>();
	}
	
	if (!MyInventory)
	{
		UE_LOG(LogTemp, Error, TEXT("ğŸ§ âŒ %s: InventoryComponent not found"), *CharName);
		return;
	}
	
	UE_LOG(LogTemp, Warning, TEXT("ğŸ§ ğŸ“¦ %s: InventoryComponent found, getting items"), *CharName);
	
	TMap<FString, int32> AllItems = MyInventory->GetAllItems();
	int32 TransferredCount = 0;
	
	UE_LOG(LogTemp, Warning, TEXT("ğŸ§ ğŸ“¦ %s: Found %d different item types in inventory"), 
		*CharName, AllItems.Num());
	
	// å…¨ã‚¢ã‚¤ãƒ†ãƒ ã‚’è»¢é€
	for (const auto& ItemPair : AllItems)
	{
		const FString& ItemId = ItemPair.Key;
		int32 Quantity = ItemPair.Value;
		
		UE_LOG(LogTemp, Warning, TEXT("ğŸ§ ğŸ“¦ %s: Processing item %s x %d"), 
			*CharName, *ItemId, Quantity);
		
		// PlayerControllerã®AddItemToStorageã‚’ç›´æ¥å‘¼ã³å‡ºã—
		PlayerController->AddItemToStorage_Implementation(ItemId, Quantity);
		TransferredCount += Quantity;
		UE_LOG(LogTemp, Warning, TEXT("ğŸ§ ğŸ“¦ %s: Transferred %d x %s to storage"), 
			*CharName, Quantity, *ItemId);
	}
	
	UE_LOG(LogTemp, Warning, TEXT("ğŸ§ ğŸ“¦ %s: Total items to transfer: %d"), 
		*CharName, TransferredCount);
	
	// ã‚¤ãƒ³ãƒ™ãƒ³ãƒˆãƒªã‹ã‚‰è»¢é€ã—ãŸã‚¢ã‚¤ãƒ†ãƒ ã‚’å‰Šé™¤
	if (TransferredCount > 0)
	{
		// è»¢é€æ¸ˆã¿ã‚¢ã‚¤ãƒ†ãƒ ã‚’å‰Šé™¤
		for (const auto& ItemPair : AllItems)
		{
			MyInventory->RemoveItem(ItemPair.Key, ItemPair.Value);
		}
		UE_LOG(LogTemp, Warning, TEXT("ğŸ§ âœ… %s: Unloaded %d items to storage"), 
			*CharName, TransferredCount);
		
		// è·ä¸‹ã‚ã—å®Œäº†å¾Œï¼šçŠ¶æ³ã‚’å†åˆ†æã—ã¦æ¬¡ã®è¡Œå‹•ã‚’æ±ºå®š
		UE_LOG(LogTemp, Warning, TEXT("ğŸ§ âœ… %s: Unload completed! Analyzing new situation..."), *CharName);
		AnalyzeMySituation();
		ConsultMyTeam(); 
		DecideMyAction();
		UE_LOG(LogTemp, Warning, TEXT("ğŸ§ ğŸ”„ %s: New action after unload: %d (%s)"), 
			*CharName, (int32)PlannedAction.ActionType, *PlannedAction.ActionReason);
	}
	else
	{
		UE_LOG(LogTemp, Warning, TEXT("ğŸ§ ğŸ“¦ %s: No items to unload"), *CharName);
	}
}

// ===========================================
// MovementServiceå‰Šé™¤ã«ä¼´ã†ãƒ˜ãƒ«ãƒ‘ãƒ¼é–¢æ•°
// ===========================================

FString AC_IdleCharacter::GetCurrentLocationDirect()
{
	// PlayerControllerã‹ã‚‰LocationMovementComponentã‚’å–å¾—
	AC_PlayerController* PC = Cast<AC_PlayerController>(
		UGameplayStatics::GetPlayerController(GetWorld(), 0));
	if (!PC)
	{
		return TEXT("base"); // ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆ
	}
	
	ULocationMovementComponent* MovementComp = PC->FindComponentByClass<ULocationMovementComponent>();
	if (!MovementComp)
	{
		return TEXT("base"); // ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆ
	}
	
	// ãƒãƒ¼ãƒ ã‚¤ãƒ³ãƒ‡ãƒƒã‚¯ã‚¹ã‚’å–å¾—
	int32 MyTeamIndex = GetTeamIndex();
	if (MyTeamIndex == -1)
	{
		return TEXT("base"); // ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆ
	}
	
	// LocationMovementComponentã‹ã‚‰ç§»å‹•æƒ…å ±ã‚’å–å¾—ã—ã¦ç¾åœ¨åœ°ã‚’åˆ¤å®š
	FMovementInfo MovementInfo = MovementComp->GetMovementInfo(MyTeamIndex);
	
	// ç§»å‹•ä¸­ã§ãªã„å ´åˆã¯ã€ç§»å‹•çŠ¶æ…‹ã«åŸºã¥ã„ã¦ç¾åœ¨åœ°ã‚’åˆ¤å®š
	if (MovementInfo.State == EMovementState::Stationary)
	{
		// ç¾åœ¨è·é›¢ãŒ0ãªã‚‰æ‹ ç‚¹
		float CurrentDistance = MovementComp->GetCurrentDistanceFromBase(MyTeamIndex);
		if (CurrentDistance <= 0.1f)
		{
			return TEXT("base");
		}
		else
		{
			// è·é›¢ã«åŸºã¥ã„ã¦å ´æ‰€ã‚’æ¨å®šï¼ˆç°¡æ˜“å®Ÿè£…ï¼‰
			return TEXT("unknown_location");
		}
	}
	else if (MovementInfo.State == EMovementState::MovingToBase)
	{
		return MovementInfo.FromLocation; // ç§»å‹•å…ƒ
	}
	else if (MovementInfo.State == EMovementState::MovingToDestination)
	{
		return MovementInfo.FromLocation; // ç§»å‹•å…ƒ
	}
	else if (MovementInfo.State == EMovementState::Arrived)
	{
		return MovementInfo.ToLocation; // åˆ°ç€åœ°
	}
	
	return TEXT("base"); // ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆ
}

bool AC_IdleCharacter::CheckMovementProgressDirect()
{
	AC_PlayerController* PC = Cast<AC_PlayerController>(
		UGameplayStatics::GetPlayerController(GetWorld(), 0));
	if (!PC)
	{
		return false;
	}
	
	ULocationMovementComponent* MovementComp = PC->FindComponentByClass<ULocationMovementComponent>();
	if (!MovementComp)
	{
		return false;
	}
	
	int32 MyTeamIndex = GetTeamIndex();
	if (MyTeamIndex == -1)
	{
		return false;
	}
	
	// ç§»å‹•çŠ¶æ…‹ã‚’ãƒã‚§ãƒƒã‚¯
	EMovementState State = MovementComp->GetMovementState(MyTeamIndex);
	return (State == EMovementState::Stationary || State == EMovementState::Arrived);
}

bool AC_IdleCharacter::MoveToLocationDirect(const FString& TargetLocation)
{
	AC_PlayerController* PC = Cast<AC_PlayerController>(
		UGameplayStatics::GetPlayerController(GetWorld(), 0));
	if (!PC)
	{
		return false;
	}
	
	ULocationMovementComponent* MovementComp = PC->FindComponentByClass<ULocationMovementComponent>();
	if (!MovementComp)
	{
		return false;
	}
	
	int32 MyTeamIndex = GetTeamIndex();
	if (MyTeamIndex == -1)
	{
		return false;
	}
	
	// ç¾åœ¨åœ°ã‚’å–å¾—
	FString CurrentLocation = GetCurrentLocationDirect();
	
	// æ—¢ã«ç›®çš„åœ°ã«ã„ã‚‹å ´åˆã¯ã‚¹ã‚­ãƒƒãƒ—
	if (CurrentLocation == TargetLocation)
	{
		return true;
	}
	
	// LocationMovementComponentã§ç§»å‹•é–‹å§‹
	return MovementComp->StartMovement(MyTeamIndex, CurrentLocation, TargetLocation);
}

int32 AC_IdleCharacter::GetTeamIndex()
{
	AC_PlayerController* PC = Cast<AC_PlayerController>(
		UGameplayStatics::GetPlayerController(GetWorld(), 0));
	if (!PC)
	{
		return -1;
	}
	
	UTeamComponent* TeamComp = PC->FindComponentByClass<UTeamComponent>();
	if (!TeamComp)
	{
		return -1;
	}
	
	// ãƒãƒ¼ãƒ ãƒ¡ãƒ³ãƒãƒ¼ã‹ã‚‰è‡ªåˆ†ã®ãƒãƒ¼ãƒ ã‚¤ãƒ³ãƒ‡ãƒƒã‚¯ã‚¹ã‚’æ¤œç´¢
	for (int32 i = 0; i < TeamComp->GetTeamCount(); i++)
	{
		FTeam Team = TeamComp->GetTeam(i);
		if (Team.Members.Contains(this))
		{
			return i;
		}
	}
	
	return -1;
}


