#include "TeamComponent.h"
#include "../Actor/C_IdleCharacter.h"
#include "../Managers/BattleSystemManager.h"
#include "InventoryComponent.h"
#include "CombatComponent.h"
#include "GatheringComponent.h"
#include "LocationMovementComponent.h"
#include "Engine/World.h"

UTeamComponent::UTeamComponent()
{
	PrimaryComponentTick.bCanEverTick = false;

	// InventoryComponentã¯å‹•çš„ã«ä½œæˆã™ã‚‹ãŸã‚ã€ã‚³ãƒ³ã‚¹ãƒˆãƒ©ã‚¯ã‚¿ã§ã¯ä½•ã‚‚ã—ãªã„
	// ãƒãƒ¼ãƒ ä½œæˆæ™‚ã«CreateTeamInventoryComponent()ã§ä½œæˆ

	// æ–°ã—ã„ã‚¿ã‚¹ã‚¯ç®¡ç†ãƒ•ã‚£ãƒ¼ãƒ«ãƒ‰ã®åˆæœŸåŒ–
	bCombatEndProcessing = false;
	bTaskSwitchProcessing = false;
	MaxTeamTasks = 3;
}

void UTeamComponent::BeginPlay()
{
	Super::BeginPlay();
	
	UE_LOG(LogTemp, Log, TEXT("TeamComponent: BeginPlay - Initialized"));
}

void UTeamComponent::BeginDestroy()
{
	// é€²è¡Œä¸­ã®å‡¦ç†ã‚’ã‚¯ãƒªã‚¢
	bCombatEndProcessing = false;
	bTaskSwitchProcessing = false;
	
	// ã‚¿ã‚¤ãƒãƒ¼ã‚’ã‚¯ãƒªã‚¢
	if (UWorld* World = GetWorld())
	{
		World->GetTimerManager().ClearAllTimersForObject(this);
	}
	
	// ã‚¿ã‚¹ã‚¯ãƒªã‚¹ãƒˆã‚’ã‚¯ãƒªã‚¢
	TeamTasks.Empty();
	
	UE_LOG(LogTemp, Log, TEXT("TeamComponent: BeginDestroy - Cleaned up"));
	
	Super::BeginDestroy();
}

void UTeamComponent::AddCharacter(AC_IdleCharacter* IdleCharacter)
{
	if (IdleCharacter && !AllPlayerCharacters.Contains(IdleCharacter))
	{
		AllPlayerCharacters.Add(IdleCharacter);
		
		// Broadcast events
		OnCharacterAdded.Broadcast(IdleCharacter);
		OnCharacterListChanged.Broadcast();
		
		UE_LOG(LogTemp, Warning, TEXT("TeamComponent: Character added, broadcasting events"));
	}
}

TArray<AC_IdleCharacter*> UTeamComponent::GetCharacterList() const
{
	return AllPlayerCharacters;
}

bool UTeamComponent::RemoveCharacter(AC_IdleCharacter* IdleCharacter)
{
	if (IdleCharacter)
	{
		if (AllPlayerCharacters.Remove(IdleCharacter) > 0)
		{
			// Broadcast events
			OnCharacterRemoved.Broadcast(IdleCharacter);
			OnCharacterListChanged.Broadcast();
			
			UE_LOG(LogTemp, Warning, TEXT("TeamComponent: Character removed, broadcasting events"));
			return true;
		}
	}
	return false;
}

int32 UTeamComponent::GetCharacterCount() const
{
	return AllPlayerCharacters.Num();
}

// ======== ãƒãƒ¼ãƒ ç®¡ç†æ©Ÿèƒ½å®Ÿè£… ========

int32 UTeamComponent::CreateTeam(const FString& TeamName)
{
	FTeam NewTeam;
	NewTeam.TeamName = TeamName;
	NewTeam.AssignedTask = ETaskType::Idle;  // ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã¯å¾…æ©Ÿ
	NewTeam.bIsActive = true;
	
	Teams.Add(NewTeam);
	int32 NewTeamIndex = Teams.Num() - 1;
	
	// TeamInventoryå‰Šé™¤ - æ–°æ¡é›†ã‚·ã‚¹ãƒ†ãƒ ã§ã¯å€‹äººã‚¤ãƒ³ãƒ™ãƒ³ãƒˆãƒªã‚’ä½¿ç”¨
	
	// æ–°ã—ã„ã‚¿ã‚¹ã‚¯ç®¡ç†ãƒ‡ãƒ¼ã‚¿ã®åˆæœŸåŒ–
	FTeamTaskList EmptyTaskList;
	TeamTasks.Add(EmptyTaskList);
	
	// ã‚¤ãƒ™ãƒ³ãƒˆé€šçŸ¥
	OnTeamCreated.Broadcast(NewTeamIndex, TeamName);
	OnTeamsUpdated.Broadcast();
	
	UE_LOG(LogTemp, Log, TEXT("CreateTeam: Created team '%s' at index %d"), *TeamName, NewTeamIndex);
	
	return NewTeamIndex;
}

bool UTeamComponent::DeleteTeam(int32 TeamIndex)
{
	if (Teams.IsValidIndex(TeamIndex))
	{
		// ãƒãƒ¼ãƒ ãƒ¡ãƒ³ãƒãƒ¼ã‚’è§£æ”¾ã™ã‚‹
		FTeam& Team = Teams[TeamIndex];
		Team.Members.Empty();
		
		// TeamInventoryå‰Šé™¤æ¸ˆã¿
		
		// å¯¾å¿œã™ã‚‹ã‚¿ã‚¹ã‚¯ãƒªã‚¹ãƒˆã‚’å‰Šé™¤
		if (TeamTasks.IsValidIndex(TeamIndex))
		{
			TeamTasks.RemoveAt(TeamIndex);
		}
		
		Teams.RemoveAt(TeamIndex);
		
		// ã‚¤ãƒ™ãƒ³ãƒˆé€šçŸ¥
		OnTeamDeleted.Broadcast(TeamIndex);
		OnTeamsUpdated.Broadcast();
		
		UE_LOG(LogTemp, Log, TEXT("DeleteTeam: Deleted team at index %d"), TeamIndex);
		
		return true;
	}
	
	UE_LOG(LogTemp, Warning, TEXT("DeleteTeam: Invalid team index %d"), TeamIndex);
	return false;
}

bool UTeamComponent::AssignCharacterToTeam(AC_IdleCharacter* Character, int32 TeamIndex)
{
	if (!Character || !Teams.IsValidIndex(TeamIndex))
	{
		return false;
	}
	
	// æ—¢ã«ä»–ã®ãƒãƒ¼ãƒ ã«æ‰€å±ã—ã¦ã„ã‚‹å ´åˆã¯è§£é™¤
	RemoveCharacterFromAllTeams(Character);
	
	// æ–°ã—ã„ãƒãƒ¼ãƒ ã«è¿½åŠ 
	Teams[TeamIndex].Members.Add(Character);
	
	// ã‚¤ãƒ™ãƒ³ãƒˆé€šçŸ¥
	UE_LOG(LogTemp, Log, TEXT("Character assigned to Team %d (%s)"), TeamIndex, *Teams[TeamIndex].TeamName);
	OnMemberAssigned.Broadcast(TeamIndex, Character, Teams[TeamIndex].TeamName);
	OnTeamsUpdated.Broadcast();
	OnCharacterDataChanged.Broadcast(Character);  // Cardã®æ›´æ–°ã‚’ãƒˆãƒªã‚¬ãƒ¼
	
	return true;
}

bool UTeamComponent::RemoveCharacterFromTeam(AC_IdleCharacter* Character, int32 TeamIndex)
{
	if (!Character || !Teams.IsValidIndex(TeamIndex))
	{
		return false;
	}
	
	bool bRemoved = Teams[TeamIndex].Members.Remove(Character) > 0;
	if (bRemoved)
	{
		// ã‚¤ãƒ™ãƒ³ãƒˆé€šçŸ¥
		OnMemberRemoved.Broadcast(TeamIndex, Character);
		OnTeamsUpdated.Broadcast();
		OnCharacterDataChanged.Broadcast(Character);  // Cardã®æ›´æ–°ã‚’ãƒˆãƒªã‚¬ãƒ¼
	}
	
	return bRemoved;
}

FTeam UTeamComponent::GetTeam(int32 TeamIndex) const
{
	if (Teams.IsValidIndex(TeamIndex))
	{
		return Teams[TeamIndex];
	}
	
	return FTeam();  // ç©ºã®ãƒãƒ¼ãƒ ã‚’è¿”ã™
}

TArray<AC_IdleCharacter*> UTeamComponent::GetUnassignedCharacters() const
{
	TArray<AC_IdleCharacter*> UnassignedList;
	
	// AllPlayerCharactersã‹ã‚‰ã€ã©ã®ãƒãƒ¼ãƒ ã«ã‚‚æ‰€å±ã—ã¦ã„ãªã„ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã‚’æŠ½å‡º
	for (AC_IdleCharacter* Character : AllPlayerCharacters)
	{
		if (Character && !IsCharacterInAnyTeam(Character))
		{
			UnassignedList.Add(Character);
		}
	}
	
	return UnassignedList;
}

bool UTeamComponent::SetTeamTask(int32 TeamIndex, ETaskType NewTask)
{
	if (Teams.IsValidIndex(TeamIndex))
	{
		Teams[TeamIndex].AssignedTask = NewTask;
		
		// å†’é™ºä»¥å¤–ã®ã‚¿ã‚¹ã‚¯ã«å¤‰æ›´ã™ã‚‹å ´åˆã¯å ´æ‰€ã‚’ã‚¯ãƒªã‚¢
		if (NewTask != ETaskType::Adventure)
		{
			Teams[TeamIndex].AdventureLocationId = TEXT("");
			Teams[TeamIndex].bInCombat = false;
		}
		
		// ã‚¤ãƒ™ãƒ³ãƒˆé€šçŸ¥
		OnTaskChanged.Broadcast(TeamIndex, NewTask);
		OnTeamsUpdated.Broadcast();
		
		return true;
	}
	return false;
}

bool UTeamComponent::SetTeamAdventureLocation(int32 TeamIndex, const FString& LocationId)
{
	if (!Teams.IsValidIndex(TeamIndex))
	{
		return false;
	}

	Teams[TeamIndex].AdventureLocationId = LocationId;
	
	// å†’é™ºå ´æ‰€ã‚’è¨­å®šã—ãŸå ´åˆã€ã‚¿ã‚¹ã‚¯ã‚‚å†’é™ºã«å¤‰æ›´
	if (!LocationId.IsEmpty() && Teams[TeamIndex].AssignedTask != ETaskType::Adventure)
	{
		Teams[TeamIndex].AssignedTask = ETaskType::Adventure;
		OnTaskChanged.Broadcast(TeamIndex, ETaskType::Adventure);
	}
	
	OnTeamsUpdated.Broadcast();
	
	UE_LOG(LogTemp, Log, TEXT("Team %d adventure location set to: %s"), TeamIndex, *LocationId);
	return true;
}

bool UTeamComponent::StartAdventure(int32 TeamIndex, const FString& LocationId)
{
	if (!Teams.IsValidIndex(TeamIndex))
	{
		UE_LOG(LogTemp, Error, TEXT("StartAdventure: Invalid team index %d"), TeamIndex);
		return false;
	}

	FTeam& Team = Teams[TeamIndex];
	
	// ãƒãƒ¼ãƒ ãƒ¡ãƒ³ãƒãƒ¼ãŒã„ã‚‹ã‹ãƒã‚§ãƒƒã‚¯
	if (Team.Members.Num() == 0)
	{
		UE_LOG(LogTemp, Error, TEXT("StartAdventure: Team %d has no members"), TeamIndex);
		return false;
	}

	// æ—¢ã«æˆ¦é—˜ä¸­ã‹ãƒã‚§ãƒƒã‚¯
	if (Team.bInCombat)
	{
		UE_LOG(LogTemp, Warning, TEXT("StartAdventure: Team %d is already in combat"), TeamIndex);
		return false;
	}

	// å ´æ‰€ã¨ã‚¿ã‚¹ã‚¯è¨­å®š
	Team.AdventureLocationId = LocationId;
	Team.AssignedTask = ETaskType::Adventure;
	Team.bInCombat = true;

	// BattleSystemManagerã‚’ä½¿ç”¨ã—ã¦ã‚¤ãƒ™ãƒ³ãƒˆãƒˆãƒªã‚¬ãƒ¼
	if (UGameInstance* GameInstance = GetWorld()->GetGameInstance())
	{
		if (UBattleSystemManager* BattleManager = GameInstance->GetSubsystem<UBattleSystemManager>())
		{
			bool bEventTriggered = BattleManager->StartTeamAdventure(Team.Members, LocationId);
			if (!bEventTriggered)
			{
				// ã‚¤ãƒ™ãƒ³ãƒˆãƒˆãƒªã‚¬ãƒ¼ã«å¤±æ•—ã—ãŸå ´åˆã¯ãƒ•ãƒ©ã‚°ã‚’ãƒªã‚»ãƒƒãƒˆ
				Team.bInCombat = false;
				UE_LOG(LogTemp, Error, TEXT("StartAdventure: Failed to trigger combat event for team %d"), TeamIndex);
				return false;
			}
		}
		else
		{
			UE_LOG(LogTemp, Error, TEXT("StartAdventure: BattleSystemManager not found"));
			Team.bInCombat = false;
			return false;
		}
	}

	// ã‚¤ãƒ™ãƒ³ãƒˆé€šçŸ¥
	OnTaskChanged.Broadcast(TeamIndex, ETaskType::Adventure);
	OnTeamsUpdated.Broadcast();

	UE_LOG(LogTemp, Log, TEXT("Adventure started for team %d at location %s with %d members"), 
		TeamIndex, *LocationId, Team.Members.Num());
	
	return true;
}

bool UTeamComponent::SetTeamGatheringLocation(int32 TeamIndex, const FString& LocationId)
{
	if (!Teams.IsValidIndex(TeamIndex))
	{
		return false;
	}

	Teams[TeamIndex].GatheringLocationId = LocationId;
	
	// æ¡é›†å ´æ‰€ã‚’è¨­å®šã—ãŸå ´åˆã€ã‚¿ã‚¹ã‚¯ã‚‚æ¡é›†ã«å¤‰æ›´
	// ãŸã ã—ã€å†’é™ºã‚¿ã‚¹ã‚¯ä¸­ã®å ´åˆã¯å¤‰æ›´ã—ãªã„
	if (!LocationId.IsEmpty() && 
		Teams[TeamIndex].AssignedTask != ETaskType::Gathering && 
		Teams[TeamIndex].AssignedTask != ETaskType::Adventure)
	{
		Teams[TeamIndex].AssignedTask = ETaskType::Gathering;
		OnTaskChanged.Broadcast(TeamIndex, ETaskType::Gathering);
	}
	
	OnTeamsUpdated.Broadcast();
	
	UE_LOG(LogTemp, Log, TEXT("Team %d gathering location set to: %s"), TeamIndex, *LocationId);
	return true;
}

bool UTeamComponent::StartGathering(int32 TeamIndex, const FString& LocationId)
{
	if (!Teams.IsValidIndex(TeamIndex))
	{
		UE_LOG(LogTemp, Error, TEXT("StartGathering: Invalid team index %d"), TeamIndex);
		return false;
	}

	FTeam& Team = Teams[TeamIndex];
	
	// ãƒãƒ¼ãƒ ãƒ¡ãƒ³ãƒãƒ¼ãŒã„ã‚‹ã‹ãƒã‚§ãƒƒã‚¯
	if (Team.Members.Num() == 0)
	{
		UE_LOG(LogTemp, Error, TEXT("StartGathering: Team %d has no members"), TeamIndex);
		return false;
	}

	// æ—¢ã«æˆ¦é—˜ä¸­ã‹ãƒã‚§ãƒƒã‚¯
	if (Team.bInCombat)
	{
		UE_LOG(LogTemp, Warning, TEXT("StartGathering: Team %d is in combat, cannot start gathering"), TeamIndex);
		return false;
	}

	// å ´æ‰€ã¨ã‚¿ã‚¹ã‚¯è¨­å®š
	Team.GatheringLocationId = LocationId;
	Team.AssignedTask = ETaskType::Gathering;

	// ã‚¤ãƒ™ãƒ³ãƒˆé€šçŸ¥
	OnTaskChanged.Broadcast(TeamIndex, ETaskType::Gathering);
	OnTeamsUpdated.Broadcast();

	UE_LOG(LogTemp, Log, TEXT("Gathering task started for team %d at location %s with %d members"), 
		TeamIndex, *LocationId, Team.Members.Num());
	
	return true;
}

int32 UTeamComponent::GetCharacterTeamIndex(AC_IdleCharacter* Character) const
{
	if (!Character)
	{
		return -1;
	}
	
	for (int32 i = 0; i < Teams.Num(); i++)
	{
		if (Teams[i].Members.Contains(Character))
		{
			return i;
		}
	}
	
	return -1;  // æœªæ‰€å±
}

bool UTeamComponent::SetTeamName(int32 TeamIndex, const FString& NewTeamName)
{
	if (Teams.IsValidIndex(TeamIndex))
	{
		Teams[TeamIndex].TeamName = NewTeamName;
		
		// ã‚¤ãƒ™ãƒ³ãƒˆé€šçŸ¥
		OnTeamNameChanged.Broadcast(TeamIndex, NewTeamName);
		OnTeamsUpdated.Broadcast();
		
		return true;
	}
	return false;
}

// ======== TaskTypeç”¨ãƒ˜ãƒ«ãƒ‘ãƒ¼é–¢æ•° ========

TArray<FString> UTeamComponent::GetAllTaskTypeNames()
{
	return {
		TEXT("å¾…æ©Ÿ"),
		TEXT("å…¨ã¦"),
		TEXT("å†’é™º"),
		TEXT("æ–™ç†")
	};
}

ETaskType UTeamComponent::GetTaskTypeFromString(const FString& TaskName)
{
	if (TaskName == TEXT("å¾…æ©Ÿ"))
		return ETaskType::Idle;
	else if (TaskName == TEXT("å…¨ã¦"))
		return ETaskType::All;
	else if (TaskName == TEXT("å†’é™º"))
		return ETaskType::Adventure;
	else if (TaskName == TEXT("æ–™ç†"))
		return ETaskType::Cooking;
	
	return ETaskType::Idle;  // ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆ
}

FString UTeamComponent::GetTaskTypeDisplayName(ETaskType TaskType)
{
	switch (TaskType)
	{
	case ETaskType::Idle:
		return TEXT("å¾…æ©Ÿ");
	case ETaskType::All:
		return TEXT("å…¨ã¦");
	case ETaskType::Adventure:
		return TEXT("å†’é™º");
	case ETaskType::Cooking:
		return TEXT("æ–™ç†");
	default:
		return TEXT("ä¸æ˜");
	}
}

TArray<ETaskType> UTeamComponent::GetAllTaskTypes()
{
	return {
		ETaskType::Idle,
		ETaskType::All,
		ETaskType::Adventure,
		ETaskType::Cooking
	};
}

FTeam UTeamComponent::CreateTeamAndGetData(const FString& TeamName, int32& OutTeamIndex)
{
	// ãƒãƒ¼ãƒ ä½œæˆ
	OutTeamIndex = CreateTeam(TeamName);
	
	// ä½œæˆã•ã‚ŒãŸãƒãƒ¼ãƒ æƒ…å ±ã‚’è¿”ã™
	if (Teams.IsValidIndex(OutTeamIndex))
	{
		return Teams[OutTeamIndex];
	}
	
	// å¤±æ•—æ™‚ã¯ç©ºã®ãƒãƒ¼ãƒ 
	OutTeamIndex = -1;
	return FTeam();
}

// ======== å†…éƒ¨ç®¡ç†é–¢æ•° ========

bool UTeamComponent::IsCharacterInAnyTeam(AC_IdleCharacter* Character) const
{
	for (const FTeam& Team : Teams)
	{
		if (Team.Members.Contains(Character))
		{
			return true;
		}
	}
	return false;
}

void UTeamComponent::RemoveCharacterFromAllTeams(AC_IdleCharacter* Character)
{
	bool bWasRemoved = false;
	for (FTeam& Team : Teams)
	{
		if (Team.Members.Remove(Character) > 0)
		{
			bWasRemoved = true;
		}
	}
	
	// ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ãŒå®Ÿéš›ã«å‰Šé™¤ã•ã‚ŒãŸå ´åˆã¯ã‚¤ãƒ™ãƒ³ãƒˆç™ºä¿¡
	if (bWasRemoved && Character)
	{
		OnCharacterDataChanged.Broadcast(Character);  // Cardã®æ›´æ–°ã‚’ãƒˆãƒªã‚¬ãƒ¼
	}
}

void UTeamComponent::OnCombatEnd(const TArray<AC_IdleCharacter*>& Winners, const TArray<AC_IdleCharacter*>& Losers)
{
	UE_LOG(LogTemp, Log, TEXT("OnCombatEnd called with %d winners and %d losers"), Winners.Num(), Losers.Num());
	
	// å‹è€…å´ã¨æ•—è€…å´ã®ä¸¡æ–¹ã®ãƒãƒ¼ãƒ ã®bInCombatãƒ•ãƒ©ã‚°ã‚’ãƒªã‚»ãƒƒãƒˆ
	TSet<int32> ProcessedTeams;
	
	// å‹è€…å´ã®ãƒãƒ¼ãƒ å‡¦ç†
	for (AC_IdleCharacter* Character : Winners)
	{
		if (Character)
		{
			int32 TeamIndex = GetCharacterTeamIndex(Character);
			if (TeamIndex >= 0 && !ProcessedTeams.Contains(TeamIndex))
			{
				if (Teams.IsValidIndex(TeamIndex))
				{
					Teams[TeamIndex].bInCombat = false;
					ProcessedTeams.Add(TeamIndex);
					UE_LOG(LogTemp, Log, TEXT("Reset bInCombat flag for team %d (%s) - Winner"), 
						TeamIndex, *Teams[TeamIndex].TeamName);
				}
			}
		}
	}
	
	// æ•—è€…å´ã®ãƒãƒ¼ãƒ å‡¦ç†
	for (AC_IdleCharacter* Character : Losers)
	{
		if (Character)
		{
			int32 TeamIndex = GetCharacterTeamIndex(Character);
			if (TeamIndex >= 0 && !ProcessedTeams.Contains(TeamIndex))
			{
				if (Teams.IsValidIndex(TeamIndex))
				{
					Teams[TeamIndex].bInCombat = false;
					ProcessedTeams.Add(TeamIndex);
					UE_LOG(LogTemp, Log, TEXT("Reset bInCombat flag for team %d (%s) - Loser"), 
						TeamIndex, *Teams[TeamIndex].TeamName);
				}
			}
		}
	}
	
	// ãƒãƒ¼ãƒ æ›´æ–°é€šçŸ¥
	OnTeamsUpdated.Broadcast();
}

// ======== æ—§ãƒãƒ¼ãƒ Inventoryæ©Ÿèƒ½ï¼ˆå‰Šé™¤ï¼‰ ========
// æ–°æ¡é›†ã‚·ã‚¹ãƒ†ãƒ ã§ã¯å€‹äººã‚¤ãƒ³ãƒ™ãƒ³ãƒˆãƒªã‚’ä½¿ç”¨

// CreateTeamInventoryComponentå‰Šé™¤ - æ–°æ¡é›†ã‚·ã‚¹ãƒ†ãƒ ã§ã¯å€‹äººã‚¤ãƒ³ãƒ™ãƒ³ãƒˆãƒªã‚’ä½¿ç”¨

// ======== æ—§ãƒãƒ¼ãƒ é‹æ¬æ‰‹æ®µæ©Ÿèƒ½ï¼ˆå‰Šé™¤ï¼‰ ========
// æ–°æ¡é›†ã‚·ã‚¹ãƒ†ãƒ ã§ã¯å€‹äººã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã®ç©è¼‰é‡ã‚’ä½¿ç”¨

// æ—§é‹æ¬æ‰‹æ®µé–¢é€£ãƒ¡ã‚½ãƒƒãƒ‰å‰Šé™¤æ¸ˆã¿
// æ–°æ¡é›†ã‚·ã‚¹ãƒ†ãƒ ã§ã¯å€‹äººã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã®ç©è¼‰é‡ã‚’GatheringComponentã§ç®¡ç†

// ======== æ–°ã—ã„ãƒãƒ¼ãƒ åˆ¥ã‚¿ã‚¹ã‚¯ç®¡ç†æ©Ÿèƒ½å®Ÿè£… ========

bool UTeamComponent::AddTeamTask(int32 TeamIndex, const FTeamTask& NewTask)
{
	if (!IsValidTeamIndex(TeamIndex))
	{
		UE_LOG(LogTemp, Warning, TEXT("AddTeamTask: Invalid team index %d"), TeamIndex);
		return false;
	}

	// ã‚¿ã‚¹ã‚¯ãƒªã‚¹ãƒˆã®ã‚µã‚¤ã‚ºç¢ºä¿
	while (TeamTasks.Num() <= TeamIndex)
	{
		FTeamTaskList EmptyTaskList;
		TeamTasks.Add(EmptyTaskList);
	}

	FTeamTaskList& TaskList = TeamTasks[TeamIndex];

	if (TaskList.Num() >= MaxTeamTasks)
	{
		UE_LOG(LogTemp, Warning, TEXT("AddTeamTask: Team %d has reached maximum task limit (%d)"), TeamIndex, MaxTeamTasks);
		return false;
	}

	if (!NewTask.IsValid())
	{
		UE_LOG(LogTemp, Warning, TEXT("AddTeamTask: Invalid task provided for team %d"), TeamIndex);
		return false;
	}

	// å„ªå…ˆåº¦é‡è¤‡ãƒã‚§ãƒƒã‚¯
	for (const FTeamTask& ExistingTask : TaskList.Tasks)
	{
		if (ExistingTask.Priority == NewTask.Priority)
		{
			UE_LOG(LogTemp, Warning, TEXT("AddTeamTask: Priority %d already exists in team %d"), NewTask.Priority, TeamIndex);
			return false;
		}
	}

	TaskList.Add(NewTask);
	
	UE_LOG(LogTemp, Log, TEXT("AddTeamTask: Added task with priority %d to team %d"), NewTask.Priority, TeamIndex);
	
	// ãƒãƒ¼ãƒ ãŒã‚¢ã‚¤ãƒ‰ãƒ«çŠ¶æ…‹ã®å ´åˆã€å³åº§ã«ã‚¿ã‚¹ã‚¯ã‚’å®Ÿè¡Œ
	if (Teams[TeamIndex].ActionState == ETeamActionState::Idle)
	{
		UE_LOG(LogTemp, Log, TEXT("AddTeamTask: Team %d is idle, attempting to execute new task"), TeamIndex);
		SwitchToNextAvailableTaskSafe(TeamIndex);
	}
	else
	{
		OnTeamTaskStarted.Broadcast(TeamIndex, NewTask);
	}
	
	return true;
}

bool UTeamComponent::RemoveTeamTask(int32 TeamIndex, int32 TaskPriority)
{
	if (!IsValidTeamIndex(TeamIndex) || !TeamTasks.IsValidIndex(TeamIndex))
	{
		return false;
	}

	FTeamTaskList& TaskList = TeamTasks[TeamIndex];
	
	for (int32 i = 0; i < TaskList.Num(); i++)
	{
		if (TaskList[i].Priority == TaskPriority)
		{
			FTeamTask RemovedTask = TaskList[i];
			TaskList.RemoveAt(i);
			
			UE_LOG(LogTemp, Log, TEXT("RemoveTeamTask: Removed task with priority %d from team %d"), TaskPriority, TeamIndex);
			
			// ã‚¿ã‚¹ã‚¯ãƒªã‚¹ãƒˆãŒç©ºã«ãªã£ãŸå ´åˆã€ãƒãƒ¼ãƒ ã‚’ã‚¢ã‚¤ãƒ‰ãƒ«çŠ¶æ…‹ã«ãƒªã‚»ãƒƒãƒˆ
			if (TaskList.Num() == 0)
			{
				Teams[TeamIndex].AssignedTask = ETaskType::Idle;
				UE_LOG(LogTemp, Log, TEXT("RemoveTeamTask: Team %d has no tasks, set to Idle"), TeamIndex);
				OnTaskChanged.Broadcast(TeamIndex, ETaskType::Idle);
			}
			
			OnTeamTaskCompleted.Broadcast(TeamIndex, RemovedTask);
			
			return true;
		}
	}

	UE_LOG(LogTemp, Warning, TEXT("RemoveTeamTask: Task with priority %d not found in team %d"), TaskPriority, TeamIndex);
	return false;
}

FTeamTask UTeamComponent::GetCurrentTeamTask(int32 TeamIndex) const
{
	if (!IsValidTeamIndex(TeamIndex) || !TeamTasks.IsValidIndex(TeamIndex))
	{
		return FTeamTask(); // ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã‚¿ã‚¹ã‚¯
	}

	const FTeamTaskList& TaskList = TeamTasks[TeamIndex];
	
	if (TaskList.Num() == 0)
	{
		return FTeamTask(); // ç©ºã®ã‚¿ã‚¹ã‚¯
	}

	// å„ªå…ˆåº¦é †ã«ã‚½ãƒ¼ãƒˆã—ã¦æœ€é«˜å„ªå…ˆåº¦ã®ã‚¿ã‚¹ã‚¯ã‚’è¿”ã™
	TArray<FTeamTask> SortedTasks = TaskList.Tasks;
	SortedTasks.Sort([](const FTeamTask& A, const FTeamTask& B) {
		return A.Priority < B.Priority;
	});

	return SortedTasks[0];
}

TArray<FTeamTask> UTeamComponent::GetTeamTasks(int32 TeamIndex) const
{
	if (IsValidTeamIndex(TeamIndex) && TeamTasks.IsValidIndex(TeamIndex))
	{
		return TeamTasks[TeamIndex].Tasks;
	}
	
	return TArray<FTeamTask>();
}

bool UTeamComponent::SwitchToNextAvailableTask(int32 TeamIndex)
{
	if (bTaskSwitchProcessing)
	{
		UE_LOG(LogTemp, Warning, TEXT("SwitchToNextAvailableTask: Already processing task switch for team %d"), TeamIndex);
		return false;
	}

	return SwitchToNextAvailableTaskSafe(TeamIndex);
}

bool UTeamComponent::SwitchToNextAvailableTaskSafe(int32 TeamIndex)
{
	if (bTaskSwitchProcessing || !IsValidTeamIndex(TeamIndex))
	{
		return false;
	}

	bTaskSwitchProcessing = true;

	bool bResult = false;

	if (TeamTasks.IsValidIndex(TeamIndex))
	{
		const FTeamTaskList& TaskList = TeamTasks[TeamIndex];
		
		// å„ªå…ˆåº¦é †ã«å®Ÿè¡Œå¯èƒ½ãªã‚¿ã‚¹ã‚¯ã‚’æ¤œç´¢
		TArray<FTeamTask> SortedTasks = TaskList.Tasks;
		SortedTasks.Sort([](const FTeamTask& A, const FTeamTask& B) {
			return A.Priority < B.Priority;
		});

		for (const FTeamTask& Task : SortedTasks)
		{
			if (CanExecuteTask(TeamIndex, Task))
			{
				ExecuteTask(TeamIndex, Task);
				OnTeamTaskSwitched.Broadcast(TeamIndex, ETaskSwitchType::Normal);
				bResult = true;
				break;
			}
		}
	}

	if (!bResult)
	{
		// å®Ÿè¡Œå¯èƒ½ãªã‚¿ã‚¹ã‚¯ãŒãªã„å ´åˆã¯å¾…æ©Ÿ
		SetTeamActionState(TeamIndex, ETeamActionState::Idle);
	}

	bTaskSwitchProcessing = false;
	return bResult;
}

bool UTeamComponent::CanExecuteTask(int32 TeamIndex, const FTeamTask& Task) const
{
	if (!IsValidTeamIndex(TeamIndex) || !Task.IsValid())
	{
		return false;
	}

	const FTeam& Team = Teams[TeamIndex];

	// ãƒãƒ¼ãƒ ãŒä¸­æ–­å¯èƒ½ãªçŠ¶æ…‹ã‹ãƒã‚§ãƒƒã‚¯
	if (!Team.CanInterruptAction())
	{
		return false;
	}

	// æœ€å°äººæ•°ãƒã‚§ãƒƒã‚¯
	if (Team.Members.Num() < Task.MinTeamSize)
	{
		return false;
	}

	// ãƒªã‚½ãƒ¼ã‚¹è¦ä»¶ãƒã‚§ãƒƒã‚¯ï¼ˆå°†æ¥çš„ã«è©³ç´°å®Ÿè£…ï¼‰
	// TODO: TaskManagerComponentã¨ã®é€£æºã§ãƒªã‚½ãƒ¼ã‚¹ãƒã‚§ãƒƒã‚¯

	return true;
}

void UTeamComponent::ExecuteTask(int32 TeamIndex, const FTeamTask& Task)
{
	if (!IsValidTeamIndex(TeamIndex) || !Task.IsValid())
	{
		return;
	}

	FTeam& Team = Teams[TeamIndex];
	
	// ã‚¿ã‚¹ã‚¯å®Ÿè¡ŒçŠ¶æ…‹ã«è¨­å®š
	Team.ActionState = ETeamActionState::Working;
	Team.AssignedTask = Task.TaskType; // ã‚¿ã‚¹ã‚¯ã‚¿ã‚¤ãƒ—ã‚’è¨­å®š
	Team.ActionStartTime = GetWorld() ? GetWorld()->GetTimeSeconds() : 0.0f;
	Team.EstimatedCompletionTime = Task.EstimatedCompletionTime * 3600.0f; // æ™‚é–“ã‚’ç§’ã«å¤‰æ›
	
	// æ¡é›†ã‚¿ã‚¹ã‚¯ã®å ´åˆã€æ—¢å­˜ã®GatheringLocationIdã‚’ä½¿ç”¨
	if (Task.TaskType == ETaskType::Gathering)
	{
		// GatheringLocationIdã¯æ—¢ã«ãƒãƒ¼ãƒ ä½œæˆæ™‚ã‚„UIæ“ä½œã§è¨­å®šã•ã‚Œã¦ã„ã‚‹ã¯ãš
		UE_LOG(LogTemp, Log, TEXT("ExecuteTask: Gathering task for team %d with location %s"), 
			TeamIndex, *Team.GatheringLocationId);
	}

	UE_LOG(LogTemp, Log, TEXT("ExecuteTask: Team %d started executing %s task with priority %d"), 
		TeamIndex, *UTaskTypeUtils::GetTaskTypeDisplayName(Task.TaskType), Task.Priority);
	OnTeamTaskStarted.Broadcast(TeamIndex, Task);
}

// ======== ãƒãƒ¼ãƒ çŠ¶æ…‹ç®¡ç†æ©Ÿèƒ½å®Ÿè£… ========

void UTeamComponent::SetTeamActionState(int32 TeamIndex, ETeamActionState NewState)
{
	if (!IsValidTeamIndex(TeamIndex))
	{
		return;
	}

	ETeamActionState OldState = Teams[TeamIndex].ActionState;
	Teams[TeamIndex].ActionState = NewState;

	if (OldState != NewState)
	{
		UE_LOG(LogTemp, Log, TEXT("SetTeamActionState: Team %d state changed from %s to %s"), 
			   TeamIndex, *UTaskTypeUtils::GetActionStateDisplayName(OldState), *UTaskTypeUtils::GetActionStateDisplayName(NewState));
		
		OnTeamActionStateChanged.Broadcast(TeamIndex, NewState);
		OnTeamsUpdated.Broadcast();
	}
}

ETeamActionState UTeamComponent::GetTeamActionState(int32 TeamIndex) const
{
	if (IsValidTeamIndex(TeamIndex))
	{
		return Teams[TeamIndex].ActionState;
	}
	
	return ETeamActionState::Idle;
}

ETaskType UTeamComponent::GetCurrentTaskType(int32 TeamIndex) const
{
	if (IsValidTeamIndex(TeamIndex))
	{
		return Teams[TeamIndex].AssignedTask;
	}
	
	return ETaskType::Idle;
}

bool UTeamComponent::CanInterruptAction(int32 TeamIndex) const
{
	if (IsValidTeamIndex(TeamIndex))
	{
		return Teams[TeamIndex].CanInterruptAction();
	}
	
	return false;
}

float UTeamComponent::GetRemainingActionTime(int32 TeamIndex) const
{
	if (IsValidTeamIndex(TeamIndex))
	{
		float CurrentTime = GetWorld() ? GetWorld()->GetTimeSeconds() : 0.0f;
		return Teams[TeamIndex].GetRemainingActionTime(CurrentTime);
	}
	
	return 0.0f;
}

bool UTeamComponent::IsValidTeamIndex(int32 TeamIndex) const
{
	return Teams.IsValidIndex(TeamIndex) && IsValid(this);
}

// ======== æˆ¦é—˜é–¢é€£æ©Ÿèƒ½å®Ÿè£…ï¼ˆå®‰å…¨æ€§å¼·åŒ–ï¼‰ ========

bool UTeamComponent::IsCombatFinished(int32 TeamIndex) const
{
	// é˜²å¾¡çš„ãƒ—ãƒ­ã‚°ãƒ©ãƒŸãƒ³ã‚° - ç¯„å›²ãƒã‚§ãƒƒã‚¯
	if (!IsValidTeamIndex(TeamIndex))
	{
		UE_LOG(LogTemp, Warning, TEXT("IsCombatFinished: Invalid TeamIndex %d"), TeamIndex);
		return false;
	}
	
	// ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆæœ‰åŠ¹æ€§ãƒã‚§ãƒƒã‚¯
	if (!IsValid(this))
	{
		UE_LOG(LogTemp, Error, TEXT("IsCombatFinished: Invalid TeamComponent"));
		return false;
	}
	
	// å‡¦ç†ä¸­ãƒ•ãƒ©ã‚°ãƒã‚§ãƒƒã‚¯ï¼ˆé‡è¤‡å‡¦ç†é˜²æ­¢ï¼‰
	if (bCombatEndProcessing)
	{
		return false;
	}
	
	// å®Ÿéš›ã®çŠ¶æ…‹åˆ¤å®š
	return Teams[TeamIndex].IsCombatFinished();
}

void UTeamComponent::StartCombat(int32 TeamIndex, float EstimatedDuration)
{
	if (!IsValidTeamIndex(TeamIndex))
	{
		return;
	}

	float CurrentTime = GetWorld() ? GetWorld()->GetTimeSeconds() : 0.0f;
	Teams[TeamIndex].StartCombatSafe(CurrentTime, EstimatedDuration);
	
	UE_LOG(LogTemp, Log, TEXT("StartCombat: Team %d entered combat (Duration: %.1fs)"), TeamIndex, EstimatedDuration);
	OnTeamActionStateChanged.Broadcast(TeamIndex, ETeamActionState::InCombat);
}

void UTeamComponent::EndCombat(int32 TeamIndex)
{
	// é‡è¤‡å‡¦ç†é˜²æ­¢
	if (bCombatEndProcessing || !IsValidTeamIndex(TeamIndex))
	{
		return;
	}
	
	// å‡¦ç†ä¸­ãƒ•ãƒ©ã‚°ã‚»ãƒƒãƒˆ
	bCombatEndProcessing = true;
	
	// çŠ¶æ…‹é·ç§»
	Teams[TeamIndex].EndCombatSafe();
	
	// ã‚¤ãƒ™ãƒ³ãƒˆé€šçŸ¥ï¼ˆéåŒæœŸå®‰å…¨ï¼‰
	GetWorld()->GetTimerManager().SetTimerForNextTick([this, TeamIndex]() {
		if (IsValid(this) && IsValidTeamIndex(TeamIndex))
		{
			Teams[TeamIndex].ActionState = ETeamActionState::Idle;
			Teams[TeamIndex].bInCombat = false;
			OnCombatEnded.Broadcast(TeamIndex);
			bCombatEndProcessing = false;
			
			UE_LOG(LogTemp, Log, TEXT("EndCombat: Team %d combat ended safely"), TeamIndex);
		}
	});
}

ETeamCombatState UTeamComponent::GetCombatState(int32 TeamIndex) const
{
	if (IsValidTeamIndex(TeamIndex))
	{
		return Teams[TeamIndex].CombatState;
	}
	
	return ETeamCombatState::NotInCombat;
}

bool UTeamComponent::IsTeamInCombat(int32 TeamIndex) const
{
	if (IsValidTeamIndex(TeamIndex))
	{
		return Teams[TeamIndex].IsInCombat();
	}
	
	return false;
}

void UTeamComponent::SetTeamCombatState(int32 TeamIndex, ETeamCombatState NewState)
{
	if (IsValidTeamIndex(TeamIndex))
	{
		Teams[TeamIndex].CombatState = NewState;
		UE_LOG(LogTemp, VeryVerbose, TEXT("SetTeamCombatState: Team %d set to %s"), 
			TeamIndex, *UEnum::GetValueAsString(NewState));
	}
}

UCombatComponent* UTeamComponent::GetCombatComponent() const
{
	// ç¾åœ¨ã®ã‚¢ã‚¯ã‚¿ãƒ¼ã®CombatComponentã‚’å–å¾—
	if (AActor* Owner = GetOwner())
	{
		return Owner->FindComponentByClass<UCombatComponent>();
	}
	
	return nullptr;
}

// === æ–°ã—ã„å§”è­²å‹å®Ÿè¡Œã‚·ã‚¹ãƒ†ãƒ å®Ÿè£… ===

// å°‚é–€ã‚³ãƒ³ãƒãƒ¼ãƒãƒ³ãƒˆå–å¾—ãƒ˜ãƒ«ãƒ‘ãƒ¼
UGatheringComponent* UTeamComponent::GetGatheringComponent() const
{
	if (AActor* Owner = GetOwner())
	{
		return Owner->FindComponentByClass<UGatheringComponent>();
	}
	return nullptr;
}

ULocationMovementComponent* UTeamComponent::GetMovementComponent() const
{
	if (AActor* Owner = GetOwner())
	{
		return Owner->FindComponentByClass<ULocationMovementComponent>();
	}
	return nullptr;
}

// å§”è­²ãƒ¡ã‚½ãƒƒãƒ‰å®Ÿè£…
bool UTeamComponent::ExecuteMovement(int32 TeamIndex, const FString& TargetLocation)
{
	UE_LOG(LogTemp, Log, TEXT("ğŸš¶ TeamComponent: Delegating movement to %s for team %d"), *TargetLocation, TeamIndex);
	
	if (!IsValidTeamIndex(TeamIndex) || TargetLocation.IsEmpty())
	{
		UE_LOG(LogTemp, Warning, TEXT("âŒ Invalid movement parameters"));
		return false;
	}
	
	ULocationMovementComponent* MovementComp = GetMovementComponent();
	if (!MovementComp)
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ MovementComponent not found"));
		return false;
	}
	
	// ãƒãƒ¼ãƒ ã®ç¾åœ¨ä½ç½®ã‚’å–å¾—ï¼ˆLocationMovementComponentã‹ã‚‰ï¼‰
	FString CurrentLocation = TEXT("base"); // ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã¯æ‹ ç‚¹
	
	// LocationMovementComponentã‹ã‚‰ç¾åœ¨ä½ç½®ã‚’å–å¾—
	float CurrentDistance = MovementComp->GetCurrentDistanceFromBase(TeamIndex);
	if (CurrentDistance <= 0.0f)
	{
		CurrentLocation = TEXT("base");
	}
	else if (FMath::IsNearlyEqual(CurrentDistance, 100.0f, 1.0f))
	{
		CurrentLocation = TEXT("plains");
	}
	else if (FMath::IsNearlyEqual(CurrentDistance, 200.0f, 1.0f))
	{
		CurrentLocation = TEXT("forest");
	}
	else if (FMath::IsNearlyEqual(CurrentDistance, 500.0f, 1.0f))
	{
		CurrentLocation = TEXT("swamp");
	}
	else if (FMath::IsNearlyEqual(CurrentDistance, 800.0f, 1.0f))
	{
		CurrentLocation = TEXT("mountain");
	}
	else
	{
		// ç§»å‹•ä¸­ã®å ´åˆã¯æœ€å¾Œã®ç›®çš„åœ°ã‚’ä½¿ç”¨
		CurrentLocation = TEXT("base");
	}
	
	UE_LOG(LogTemp, Log, TEXT("ğŸ—ºï¸ Team %d current location: %s (distance: %.1f)"), TeamIndex, *CurrentLocation, CurrentDistance);
	
	// æ—¢ã«ç›®çš„åœ°ã«ã„ã‚‹ã‹ãƒã‚§ãƒƒã‚¯
	if (CurrentLocation == TargetLocation)
	{
		UE_LOG(LogTemp, Log, TEXT("ğŸ Team %d is already at %s, skipping movement"), TeamIndex, *TargetLocation);
		SetTeamActionState(TeamIndex, ETeamActionState::Working);
		return true;
	}
	
	// LocationMovementComponentã«ç§»å‹•é–‹å§‹ã‚’å§”è­²
	bool bMovementStarted = MovementComp->StartMovement(TeamIndex, CurrentLocation, TargetLocation);
	if (!bMovementStarted)
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ Failed to start movement for team %d"), TeamIndex);
		return false;
	}
	
	// ãƒãƒ¼ãƒ çŠ¶æ…‹ã‚’æ›´æ–°
	SetTeamGatheringLocation(TeamIndex, TargetLocation);
	SetTeamActionState(TeamIndex, ETeamActionState::Moving);
	
	UE_LOG(LogTemp, Log, TEXT("âœ… Movement initiated to %s"), *TargetLocation);
	return true;
}

bool UTeamComponent::ExecuteGathering(int32 TeamIndex, const FString& TargetItem)
{
	UE_LOG(LogTemp, Log, TEXT("ğŸŒ¾ TeamComponent: Delegating gathering of %s for team %d"), *TargetItem, TeamIndex);
	
	if (!IsValidTeamIndex(TeamIndex) || TargetItem.IsEmpty())
	{
		UE_LOG(LogTemp, Warning, TEXT("âŒ Invalid gathering parameters"));
		return false;
	}
	
	UGatheringComponent* GatheringComp = GetGatheringComponent();
	if (!GatheringComp)
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ GatheringComponent not found"));
		return false;
	}
	
	// ãƒãƒ¼ãƒ ã®ç¾åœ¨ä½ç½®ã‚’å–å¾—ï¼ˆLocationMovementComponentã‹ã‚‰ï¼‰
	ULocationMovementComponent* MovementComp = GetMovementComponent();
	FString CurrentLocation = TEXT("base");
	
	if (MovementComp)
	{
		float CurrentDistance = MovementComp->GetCurrentDistanceFromBase(TeamIndex);
		if (CurrentDistance <= 0.0f)
		{
			CurrentLocation = TEXT("base");
		}
		else if (FMath::IsNearlyEqual(CurrentDistance, 100.0f, 1.0f))
		{
			CurrentLocation = TEXT("plains");
		}
		else if (FMath::IsNearlyEqual(CurrentDistance, 200.0f, 1.0f))
		{
			CurrentLocation = TEXT("forest");
		}
		else if (FMath::IsNearlyEqual(CurrentDistance, 500.0f, 1.0f))
		{
			CurrentLocation = TEXT("swamp");
		}
		else if (FMath::IsNearlyEqual(CurrentDistance, 800.0f, 1.0f))
		{
			CurrentLocation = TEXT("mountain");
		}
	}
	
	UE_LOG(LogTemp, Warning, TEXT("ğŸŒ¾ ExecuteGathering: Team %d at location %s"), TeamIndex, *CurrentLocation);
	
	// GatheringComponentã«æ¡é›†å ´æ‰€ã‚’ç™»éŒ²
	GatheringComp->SetTeamTargetLocation(TeamIndex, CurrentLocation);
	
	// GatheringComponentã«æ¡é›†å‡¦ç†ã‚’å§”è­²
	GatheringComp->ProcessTeamGatheringWithTarget(TeamIndex, TargetItem);
	SetTeamActionState(TeamIndex, ETeamActionState::Working);
	
	UE_LOG(LogTemp, Log, TEXT("âœ… Gathering initiated for %s"), *TargetItem);
	return true;
}

bool UTeamComponent::ExecuteCombat(int32 TeamIndex, const FString& TargetLocation)
{
	UE_LOG(LogTemp, Log, TEXT("âš”ï¸ TeamComponent: Delegating combat at %s for team %d"), *TargetLocation, TeamIndex);
	
	if (!IsValidTeamIndex(TeamIndex))
	{
		UE_LOG(LogTemp, Warning, TEXT("âŒ Invalid combat parameters"));
		return false;
	}
	
	UCombatComponent* CombatComp = GetCombatComponent();
	if (!CombatComp)
	{
		UE_LOG(LogTemp, Error, TEXT("âŒ CombatComponent not found"));
		return false;
	}
	
	// æˆ¦é—˜ä¸­ã§ãªã‘ã‚Œã°æˆ¦é—˜é–‹å§‹
	if (!CombatComp->IsInCombat())
	{
		// TODO: æ•µç”Ÿæˆã‚·ã‚¹ãƒ†ãƒ ã¨é€£æº
		TArray<AC_IdleCharacter*> EnemyTeam; // ä¸€æ™‚çš„ã«ç©ºã®æ•µãƒãƒ¼ãƒ 
		
		FTeam Team = GetTeam(TeamIndex);
		bool bCombatStarted = CombatComp->StartCombatSimple(Team.Members, EnemyTeam);
		
		if (bCombatStarted)
		{
			SetTeamActionState(TeamIndex, ETeamActionState::InCombat);
			UE_LOG(LogTemp, Log, TEXT("âœ… Combat started for team %d"), TeamIndex);
			return true;
		}
		else
		{
			UE_LOG(LogTemp, Warning, TEXT("âŒ Failed to start combat for team %d"), TeamIndex);
			return false;
		}
	}
	else
	{
		// æˆ¦é—˜ç¶™ç¶šä¸­ - CombatComponent::ProcessCombat()ã§1ã‚¿ãƒ¼ãƒ³å‡¦ç†
		CombatComp->ProcessCombat(0.0f);
		UE_LOG(LogTemp, VeryVerbose, TEXT("âš”ï¸ Processing combat turn for team %d"), TeamIndex);
		return true;
	}
}

bool UTeamComponent::ExecuteUnload(int32 TeamIndex)
{
	UE_LOG(LogTemp, Log, TEXT("ğŸ“¦ TeamComponent: Delegating unload for team %d"), TeamIndex);
	
	if (!IsValidTeamIndex(TeamIndex))
	{
		UE_LOG(LogTemp, Warning, TEXT("âŒ Invalid unload parameters"));
		return false;
	}
	
	// TODO: TimeManagerã®AutoUnloadResourceItems()ãƒ­ã‚¸ãƒƒã‚¯ã‚’å§”è­²
	// ä¸€æ™‚çš„ãªå®Ÿè£…ï¼šå‡¦ç†å®Œäº†ãƒ•ãƒ©ã‚°
	UE_LOG(LogTemp, Log, TEXT("âœ… Unload completed for team %d"), TeamIndex);
	return true;
}

// ãƒ¡ã‚¤ãƒ³ã®å®Ÿè¡Œãƒ¡ã‚½ãƒƒãƒ‰
bool UTeamComponent::ExecutePlan(const FTaskExecutionPlan& Plan, int32 TeamIndex)
{
	UE_LOG(LogTemp, Log, TEXT("ğŸ“‹ TeamComponent: Executing plan for team %d - %s"), TeamIndex, *Plan.ExecutionReason);
	
	if (!Plan.bIsValid)
	{
		UE_LOG(LogTemp, Warning, TEXT("âŒ Invalid execution plan"));
		return false;
	}
	
	switch (Plan.ExecutionAction)
	{
		case ETaskExecutionAction::MoveToLocation:
			return ExecuteMovement(TeamIndex, Plan.TargetLocation);
			
		case ETaskExecutionAction::ExecuteGathering:
			return ExecuteGathering(TeamIndex, Plan.TargetItem);
			
		case ETaskExecutionAction::ExecuteCombat:
			return ExecuteCombat(TeamIndex, Plan.TargetLocation);
			
		case ETaskExecutionAction::ReturnToBase:
			return ExecuteMovement(TeamIndex, TEXT("base"));
			
		case ETaskExecutionAction::UnloadItems:
			return ExecuteUnload(TeamIndex);
			
		case ETaskExecutionAction::WaitIdle:
			SetToIdle(TeamIndex);
			return true;
			
		case ETaskExecutionAction::None:
		default:
			UE_LOG(LogTemp, Warning, TEXT("âŒ Unsupported execution action: %d"), (int32)Plan.ExecutionAction);
			SetToIdle(TeamIndex);
			return false;
	}
}

void UTeamComponent::SetToIdle(int32 TeamIndex)
{
	UE_LOG(LogTemp, Log, TEXT("ğŸ’¤ TeamComponent: Setting team %d to idle"), TeamIndex);
	
	if (IsValidTeamIndex(TeamIndex))
	{
		SetTeamActionState(TeamIndex, ETeamActionState::Idle);
	}
}

// === TimeManagerComponentç”¨ã‚¢ã‚¯ã‚»ã‚µãƒ¼å®Ÿè£… ===

void UTeamComponent::SetTeamActionStateInternal(int32 TeamIndex, ETeamActionState NewState, float ActionStartTime, float EstimatedCompletionTime)
{
	if (!Teams.IsValidIndex(TeamIndex))
	{
		UE_LOG(LogTemp, Error, TEXT("SetTeamActionStateInternal: Invalid team index %d"), TeamIndex);
		return;
	}
	
	FTeam& Team = Teams[TeamIndex];
	Team.ActionState = NewState;
	Team.ActionStartTime = ActionStartTime;
	Team.EstimatedCompletionTime = EstimatedCompletionTime;
	
	// ã‚¤ãƒ™ãƒ³ãƒˆé€šçŸ¥
	OnTeamActionStateChanged.Broadcast(TeamIndex, NewState);
}
