#include "TimeManagerComponent.h"
#include "../Actor/C_IdleCharacter.h"
#include "../C_PlayerController.h"
#include "TeamComponent.h"
#include "Engine/World.h"
#include "Kismet/GameplayStatics.h"

// ===========================================
// Phase 3: ç°¡ç´ åŒ–ã•ã‚ŒãŸTimeManagerComponentå®Ÿè£…
// å”¯ä¸€ã®è²¬ä»»ï¼šå…¨ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã«ã‚¿ãƒ¼ãƒ³é–‹å§‹é€šçŸ¥ã‚’é€ã‚‹ã“ã¨
// ===========================================

UTimeManagerComponent::UTimeManagerComponent()
{
    PrimaryComponentTick.bCanEverTick = false;
    
    // ç°¡ç´ åŒ–ã•ã‚ŒãŸåˆæœŸåŒ–
    bTimeSystemActive = false;
    TimeUpdateInterval = 1.0f;  // 1ç§’ = 1ã‚¿ãƒ¼ãƒ³
    CurrentTurn = 0;
    bGamePaused = false;
    CurrentGameSpeed = "Normal";
    
    // ã‚²ãƒ¼ãƒ é€Ÿåº¦ãƒ—ãƒªã‚»ãƒƒãƒˆåˆæœŸåŒ–
    GameSpeedPresets.Add("Slow", 2.0f);
    GameSpeedPresets.Add("Normal", 1.0f);
    GameSpeedPresets.Add("Fast", 0.5f);
    GameSpeedPresets.Add("Ultra", 0.1f);
    
    UE_LOG(LogTemp, Log, TEXT("ğŸ• Simplified TimeManagerComponent created with game speed control"));
}

void UTimeManagerComponent::BeginPlay()
{
    Super::BeginPlay();
    
    UE_LOG(LogTemp, Log, TEXT("ğŸ• Simplified TimeManagerComponent: BeginPlay - Ready for autonomous character system"));
}

void UTimeManagerComponent::BeginDestroy()
{
    // ã‚·ã‚¹ãƒ†ãƒ åœæ­¢
    StopTimeSystem();
    
    UE_LOG(LogTemp, Log, TEXT("ğŸ• Simplified TimeManagerComponent: BeginDestroy - Clean shutdown"));
    
    Super::BeginDestroy();
}

// ===========================================
// Phase 3: ç°¡ç´ åŒ–ã•ã‚ŒãŸãƒ‘ãƒ–ãƒªãƒƒã‚¯APIå®Ÿè£…
// ===========================================

void UTimeManagerComponent::StartTimeSystem()
{
    if (bTimeSystemActive)
    {
        UE_LOG(LogTemp, Warning, TEXT("ğŸ• Time system is already active"));
        return;
    }

    bTimeSystemActive = true;
    SetupTimer();
    
    UE_LOG(LogTemp, Log, TEXT("ğŸ• Autonomous time system started - Turn interval: %.1f seconds"), TimeUpdateInterval);
}

void UTimeManagerComponent::StopTimeSystem()
{
    if (!bTimeSystemActive)
    {
        return;
    }

    bTimeSystemActive = false;
    ClearTimer();
    
    UE_LOG(LogTemp, Log, TEXT("ğŸ• Autonomous time system stopped at turn %d"), CurrentTurn);
}

void UTimeManagerComponent::ProcessTimeUpdate()
{
    // å®Ÿè£…è¨ˆç”»æ›¸ã«è¨˜è¼‰ã•ã‚ŒãŸæ–°ã—ã„è¨­è¨ˆã«å¾“ã†
    // å”¯ä¸€ã®è²¬ä»»ï¼šã‚¿ãƒ¼ãƒ³é–‹å§‹é€šçŸ¥
    
    if (!bTimeSystemActive || bGamePaused)
    {
        return;
    }

    // ã‚¿ãƒ¼ãƒ³ç•ªå·ã‚’é€²ã‚ã‚‹
    CurrentTurn++;
    
    // ã‚¿ãƒ¼ãƒ³é–‹å§‹ã®ç›®ç«‹ã¤åŒºåˆ‡ã‚Šç·šã‚’è¿½åŠ 
    UE_LOG(LogTemp, Warning, TEXT("â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– â– "));
    
    // UE_LOG(LogTemp, Verbose, TEXT("ğŸ•â° Turn %d started - Notifying all autonomous characters"), CurrentTurn);
    
    // ğŸš¨ CRITICAL FIX: ãƒãƒ¼ãƒ æˆ¦ç•¥ã®å®šæœŸæ›´æ–°
    // å®Ÿè£…è¨ˆç”»æ›¸ï¼šã€Œæ—¢å­˜æ©Ÿèƒ½ã®å®Œå…¨å†ç¾ã€ã‚’ä¿è¨¼
    // UIã‹ã‚‰ã®ã‚¿ã‚¹ã‚¯å¤‰æ›´ã«åŠ ãˆã¦ã€çŠ¶æ³å¤‰åŒ–ã«å¿œã˜ãŸæˆ¦ç•¥æ›´æ–°
    if (CurrentTurn % 10 == 0) // 10ã‚¿ãƒ¼ãƒ³æ¯ã«æˆ¦ç•¥ã‚’å†è©•ä¾¡
    {
        AC_PlayerController* PlayerController = Cast<AC_PlayerController>(
            UGameplayStatics::GetPlayerController(GetWorld(), 0));
        if (PlayerController)
        {
            UTeamComponent* TeamComp = PlayerController->FindComponentByClass<UTeamComponent>();
            if (TeamComp)
            {
                TeamComp->ReevaluateAllTeamStrategies();
                UE_LOG(LogTemp, VeryVerbose, TEXT("ğŸ•ğŸ¯ Turn %d: Team strategies reevaluated"), CurrentTurn);
            }
        }
    }
    
    // ğŸš¨ UPDATED: ã‚°ãƒªãƒƒãƒ‰ãƒ™ãƒ¼ã‚¹ç§»å‹•ã‚·ã‚¹ãƒ†ãƒ çµ±åˆ
    // è‡ªå¾‹çš„ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ãŒå€‹åˆ¥ã«ç§»å‹•ã‚’åˆ¤æ–­ã™ã‚‹ãŸã‚ã€TimeManagerã¯åŸºæœ¬çš„ãªæ›´æ–°ã®ã¿
    AC_PlayerController* MovementPlayerController = Cast<AC_PlayerController>(
        UGameplayStatics::GetPlayerController(GetWorld(), 0));
    if (MovementPlayerController)
    {
        UTeamComponent* TeamComp = MovementPlayerController->FindComponentByClass<UTeamComponent>();
        
        if (TeamComp)
        {
            // ãƒãƒ¼ãƒ çŠ¶æ³ã®åŸºæœ¬æ›´æ–°ã®ã¿å®Ÿè¡Œ
            // å®Ÿéš›ã®ç§»å‹•ã¯Behavior TreeãŒå„ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼å€‹åˆ¥ã«å‡¦ç†
            
            // UIæ›´æ–°ã¯å¼•ãç¶šãå®Ÿè¡Œï¼ˆãƒãƒ¼ãƒ çŠ¶æ³å¤‰åŒ–ã®åæ˜ ï¼‰
            TeamComp->OnTeamsUpdated.Broadcast();
            UE_LOG(LogTemp, VeryVerbose, TEXT("ğŸ•ğŸ® Turn %d: Team status updated for autonomous system"), 
                CurrentTurn);
        }
    }
    
    // å…¨ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã«ã‚¿ãƒ¼ãƒ³é–‹å§‹ã‚’é€šçŸ¥
    TArray<AActor*> AllCharacters;
    UGameplayStatics::GetAllActorsOfClass(GetWorld(), AC_IdleCharacter::StaticClass(), AllCharacters);
    
    int32 NotifiedCharacters = 0;
    
    for (AActor* Actor : AllCharacters)
    {
        if (AC_IdleCharacter* Character = Cast<AC_IdleCharacter>(Actor))
        {
            // å„ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã®è‡ªå¾‹çš„å‡¦ç†ã‚’é–‹å§‹
            Character->OnTurnTick(CurrentTurn);
            NotifiedCharacters++;
        }
    }
    
    // UE_LOG(LogTemp, Verbose, TEXT("ğŸ•âœ… Turn %d completed - Notified %d characters"), 
    //     CurrentTurn, NotifiedCharacters);
    
    // ãã‚Œã ã‘ï¼
    // è¤‡é›‘ãªã‚¿ã‚¹ã‚¯å‡¦ç†ã€ãƒãƒ¼ãƒ ç®¡ç†ã€ãƒªã‚½ãƒ¼ã‚¹ç›£è¦–ãªã©ã¯
    // è‡ªå¾‹çš„ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã‚·ã‚¹ãƒ†ãƒ ã¨ã‚µãƒ¼ãƒ“ã‚¹ç¾¤ãŒæ‹…å½“
}

// ===========================================
// Phase 3: ç°¡ç´ åŒ–ã•ã‚ŒãŸå†…éƒ¨å®Ÿè£…
// ===========================================

void UTimeManagerComponent::SetupTimer()
{
    if (!GetWorld())
    {
        UE_LOG(LogTemp, Error, TEXT("ğŸ•âŒ Cannot setup timer - World is null"));
        return;
    }

    GetWorld()->GetTimerManager().SetTimer(
        TimeUpdateTimerHandle,
        this,
        &UTimeManagerComponent::ProcessTimeUpdate,
        TimeUpdateInterval,
        true  // Loop
    );
    
    UE_LOG(LogTemp, Verbose, TEXT("ğŸ•â²ï¸ Timer setup complete - Interval: %.1f seconds"), TimeUpdateInterval);
}

void UTimeManagerComponent::ClearTimer()
{
    if (GetWorld() && TimeUpdateTimerHandle.IsValid())
    {
        GetWorld()->GetTimerManager().ClearTimer(TimeUpdateTimerHandle);
        TimeUpdateTimerHandle.Invalidate();
        
        UE_LOG(LogTemp, Verbose, TEXT("ğŸ•â¹ï¸ Timer cleared"));
    }
}

// ===============================================
// ã‚²ãƒ¼ãƒ é€Ÿåº¦åˆ¶å¾¡å®Ÿè£…
// ===============================================

void UTimeManagerComponent::SetGameSpeed(const FString& SpeedName)
{
    if (const float* Speed = GameSpeedPresets.Find(SpeedName))
    {
        CurrentGameSpeed = SpeedName;
        SetCustomInterval(*Speed);
        
        UE_LOG(LogTemp, Log, TEXT("ğŸ•âš¡ Game speed set to %s (%.2f seconds per turn)"), 
            *SpeedName, *Speed);
    }
    else
    {
        UE_LOG(LogTemp, Warning, TEXT("ğŸ•âŒ Unknown game speed: %s"), *SpeedName);
    }
}

void UTimeManagerComponent::SetCustomInterval(float NewInterval)
{
    if (NewInterval < 0.1f || NewInterval > 10.0f)
    {
        UE_LOG(LogTemp, Warning, TEXT("ğŸ•âŒ Invalid interval: %.2f (must be 0.1-10.0)"), NewInterval);
        return;
    }

    TimeUpdateInterval = NewInterval;
    
    // ã‚¿ã‚¤ãƒãƒ¼ãŒå‹•ã„ã¦ã„ã‚‹å ´åˆã¯å†è¨­å®š
    if (bTimeSystemActive)
    {
        StopTimeSystem();
        StartTimeSystem();
    }
    
    UE_LOG(LogTemp, Log, TEXT("ğŸ•âš™ï¸ Custom interval set to %.2f seconds"), NewInterval);
}

void UTimeManagerComponent::PauseGame()
{
    if (!bGamePaused)
    {
        bGamePaused = true;
        UE_LOG(LogTemp, Log, TEXT("ğŸ•â¸ï¸ Game paused at turn %d"), CurrentTurn);
    }
}

void UTimeManagerComponent::ResumeGame()
{
    if (bGamePaused)
    {
        bGamePaused = false;
        UE_LOG(LogTemp, Log, TEXT("ğŸ•â–¶ï¸ Game resumed at turn %d"), CurrentTurn);
    }
}